// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const bhs = Country(
    id: 17,
    name: 'Bahamas The',
    iso3: 'BHS',
    iso2: 'BS',
    phoneCode: '+1-242',
    capital: 'Nassau',
    currency: 'BSD',
    currencySymbol: r'B$',
    tld: '.bs',
    native: 'Bahamas',
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: [
      Timezone(
          zoneName: 'America/Nassau',
          gmtOffset: -18000,
          gmtOffsetName: 'UTC-05:00',
          abbreviation: 'EST',
          tzName: 'Eastern Standard Time (North America)')
    ],
    emoji: '🇧🇸',
    emojiU: 'U+1F1E7 U+1F1F8',
    states: [
      State(id: 3601, name: 'Acklins', stateCode: 'AK', cities: []),
      State(
          id: 3628,
          name: 'Acklins and Crooked Islands',
          stateCode: 'AC',
          cities: []),
      State(id: 3593, name: 'Berry Islands', stateCode: 'BY', cities: []),
      State(id: 3629, name: 'Bimini', stateCode: 'BI', cities: [
        City(
            id: 15686,
            name: 'Alice Town',
            latitude: '25.72800000',
            longitude: '-79.29721000')
      ]),
      State(id: 3605, name: 'Black Point', stateCode: 'BP', cities: []),
      State(id: 3611, name: 'Cat Island', stateCode: 'CI', cities: [
        City(
            id: 15688,
            name: 'Arthur’s Town',
            latitude: '24.62240000',
            longitude: '-75.67151000')
      ]),
      State(id: 3603, name: 'Central Abaco', stateCode: 'CO', cities: [
        City(
            id: 15699,
            name: 'Marsh Harbour',
            latitude: '26.54124000',
            longitude: '-77.06360000')
      ]),
      State(id: 3631, name: 'Central Andros', stateCode: 'CS', cities: []),
      State(id: 3596, name: 'Central Eleuthera', stateCode: 'CE', cities: []),
      State(id: 3621, name: 'Crooked Island', stateCode: 'CK', cities: [
        City(
            id: 15691,
            name: 'Colonel Hill',
            latitude: '22.75450000',
            longitude: '-74.20415000')
      ]),
      State(id: 3614, name: 'East Grand Bahama', stateCode: 'EG', cities: [
        City(
            id: 15697,
            name: 'High Rock',
            latitude: '26.60999000',
            longitude: '-78.27863000')
      ]),
      State(id: 3612, name: 'Exuma', stateCode: 'EX', cities: [
        City(
            id: 15696,
            name: 'George Town',
            latitude: '23.51616000',
            longitude: '-75.78665000')
      ]),
      State(id: 3626, name: 'Freeport', stateCode: 'FP', cities: [
        City(
            id: 15695,
            name: 'Freeport',
            latitude: '26.53333000',
            longitude: '-78.70000000'),
        City(
            id: 15698,
            name: 'Lucaya',
            latitude: '26.53333000',
            longitude: '-78.66667000')
      ]),
      State(id: 3619, name: 'Fresh Creek', stateCode: 'FC', cities: []),
      State(id: 3597, name: 'Governor\'s Harbour', stateCode: 'GH', cities: []),
      State(id: 3632, name: 'Grand Cay', stateCode: 'GC', cities: []),
      State(id: 3595, name: 'Green Turtle Cay', stateCode: 'GT', cities: []),
      State(id: 3613, name: 'Harbour Island', stateCode: 'HI', cities: [
        City(
            id: 15694,
            name: 'Dunmore Town',
            latitude: '25.50216000',
            longitude: '-76.63633000')
      ]),
      State(id: 3598, name: 'High Rock', stateCode: 'HR', cities: []),
      State(id: 3624, name: 'Hope Town', stateCode: 'HT', cities: []),
      State(id: 3609, name: 'Inagua', stateCode: 'IN', cities: [
        City(
            id: 15700,
            name: 'Matthew Town',
            latitude: '20.94982000',
            longitude: '-73.67346000')
      ]),
      State(id: 3618, name: 'Kemps Bay', stateCode: 'KB', cities: []),
      State(id: 3610, name: 'Long Island', stateCode: 'LI', cities: [
        City(
            id: 15689,
            name: 'Clarence Town',
            latitude: '23.10000000',
            longitude: '-74.98333000')
      ]),
      State(id: 3625, name: 'Mangrove Cay', stateCode: 'MC', cities: []),
      State(id: 3604, name: 'Marsh Harbour', stateCode: 'MH', cities: []),
      State(id: 3633, name: 'Mayaguana District', stateCode: 'MG', cities: [
        City(
            id: 15685,
            name: 'Abraham’s Bay',
            latitude: '22.36667000',
            longitude: '-72.96667000')
      ]),
      State(id: 4881, name: 'New Providence', stateCode: 'NP', cities: [
        City(
            id: 143913,
            name: 'Nassau',
            latitude: '25.06666667',
            longitude: '-77.33333333')
      ]),
      State(
          id: 3594,
          name: 'Nichollstown and Berry Islands',
          stateCode: 'NB',
          cities: []),
      State(id: 3616, name: 'North Abaco', stateCode: 'NO', cities: [
        City(
            id: 15692,
            name: 'Cooper’s Town',
            latitude: '26.87137000',
            longitude: '-77.51131000')
      ]),
      State(id: 3617, name: 'North Andros', stateCode: 'NS', cities: [
        City(
            id: 15687,
            name: 'Andros Town',
            latitude: '24.70502000',
            longitude: '-77.76912000'),
        City(
            id: 15702,
            name: 'San Andros',
            latitude: '25.06667000',
            longitude: '-78.05000000')
      ]),
      State(id: 3602, name: 'North Eleuthera', stateCode: 'NE', cities: []),
      State(id: 3615, name: 'Ragged Island', stateCode: 'RI', cities: [
        City(
            id: 15693,
            name: 'Duncan Town',
            latitude: '22.19083000',
            longitude: '-75.72583000')
      ]),
      State(id: 3623, name: 'Rock Sound', stateCode: 'RS', cities: []),
      State(id: 3600, name: 'Rum Cay District', stateCode: 'RC', cities: [
        City(
            id: 15701,
            name: 'Port Nelson',
            latitude: '23.64967000',
            longitude: '-74.84157000')
      ]),
      State(
          id: 3620,
          name: 'San Salvador and Rum Cay',
          stateCode: 'SR',
          cities: []),
      State(id: 3627, name: 'San Salvador Island', stateCode: 'SS', cities: [
        City(
            id: 15690,
            name: 'Cockburn Town',
            latitude: '24.05179000',
            longitude: '-74.53138000')
      ]),
      State(id: 3606, name: 'Sandy Point', stateCode: 'SP', cities: []),
      State(id: 3608, name: 'South Abaco', stateCode: 'SO', cities: []),
      State(id: 3622, name: 'South Andros', stateCode: 'SA', cities: []),
      State(id: 3607, name: 'South Eleuthera', stateCode: 'SE', cities: []),
      State(id: 3630, name: 'Spanish Wells', stateCode: 'SW', cities: [
        City(
            id: 15703,
            name: 'Spanish Wells',
            latitude: '25.54717000',
            longitude: '-76.76405000')
      ]),
      State(id: 3599, name: 'West Grand Bahama', stateCode: 'WG', cities: [
        City(
            id: 15704,
            name: 'West End',
            latitude: '26.68711000',
            longitude: '-78.97702000')
      ])
    ]);
