// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const grd = Country(
    id: 87,
    name: 'Grenada',
    iso3: 'GRD',
    iso2: 'GD',
    phoneCode: '+1-473',
    capital: 'St. George\'s',
    currency: 'XCD',
    currencySymbol: r'$',
    tld: '.gd',
    native: 'Grenada',
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: [
      Timezone(
          zoneName: 'America/Grenada',
          gmtOffset: -14400,
          gmtOffsetName: 'UTC-04:00',
          abbreviation: 'AST',
          tzName: 'Atlantic Standard Time')
    ],
    emoji: '🇬🇩',
    emojiU: 'U+1F1EC U+1F1E9',
    states: [
      State(
          id: 3867,
          name: 'Carriacou and Petite Martinique',
          stateCode: '10',
          cities: [
            City(
                id: 52030,
                name: 'Hillsborough',
                latitude: '12.48292000',
                longitude: '-61.45597000')
          ]),
      State(id: 3865, name: 'Saint Andrew Parish', stateCode: '01', cities: [
        City(
            id: 52029,
            name: 'Grenville',
            latitude: '12.12278000',
            longitude: '-61.62498000')
      ]),
      State(id: 3869, name: 'Saint David Parish', stateCode: '02', cities: [
        City(
            id: 52031,
            name: 'Saint David’s',
            latitude: '12.04903000',
            longitude: '-61.66875000')
      ]),
      State(id: 3864, name: 'Saint George Parish', stateCode: '03', cities: [
        City(
            id: 52032,
            name: 'Saint George\'s',
            latitude: '12.05288000',
            longitude: '-61.75226000')
      ]),
      State(id: 3868, name: 'Saint John Parish', stateCode: '04', cities: [
        City(
            id: 52028,
            name: 'Gouyave',
            latitude: '12.16462000',
            longitude: '-61.72965000')
      ]),
      State(id: 3866, name: 'Saint Mark Parish', stateCode: '05', cities: [
        City(
            id: 52034,
            name: 'Victoria',
            latitude: '12.19021000',
            longitude: '-61.70677000')
      ]),
      State(id: 3863, name: 'Saint Patrick Parish', stateCode: '06', cities: [
        City(
            id: 52033,
            name: 'Sauteurs',
            latitude: '12.21833000',
            longitude: '-61.63917000')
      ])
    ]);
