// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const bdi = Country(
    id: 36,
    name: 'Burundi',
    iso3: 'BDI',
    iso2: 'BI',
    phoneCode: '257',
    capital: 'Bujumbura',
    currency: 'BIF',
    currencySymbol: r'FBu',
    tld: '.bi',
    native: 'Burundi',
    region: 'Africa',
    subregion: 'Eastern Africa',
    timezones: [
      Timezone(
          zoneName: 'Africa/Bujumbura',
          gmtOffset: 7200,
          gmtOffsetName: 'UTC+02:00',
          abbreviation: 'CAT',
          tzName: 'Central Africa Time')
    ],
    emoji: '🇧🇮',
    emojiU: 'U+1F1E7 U+1F1EE',
    states: [
      State(id: 3196, name: 'Bubanza Province', stateCode: 'BB', cities: [
        City(
            id: 9762,
            name: 'Bubanza',
            latitude: '-3.08040000',
            longitude: '29.39100000')
      ]),
      State(
          id: 3198,
          name: 'Bujumbura Mairie Province',
          stateCode: 'BM',
          cities: [
            City(
                id: 9763,
                name: 'Bujumbura',
                latitude: '-3.38193000',
                longitude: '29.36142000')
          ]),
      State(
          id: 3200,
          name: 'Bujumbura Rural Province',
          stateCode: 'BL',
          cities: []),
      State(id: 3202, name: 'Bururi Province', stateCode: 'BR', cities: [
        City(
            id: 9764,
            name: 'Bururi',
            latitude: '-3.94877000',
            longitude: '29.62438000')
      ]),
      State(id: 3201, name: 'Cankuzo Province', stateCode: 'CA', cities: [
        City(
            id: 9765,
            name: 'Cankuzo',
            latitude: '-3.21860000',
            longitude: '30.55280000')
      ]),
      State(id: 3190, name: 'Cibitoke Province', stateCode: 'CI', cities: [
        City(
            id: 9766,
            name: 'Cibitoke',
            latitude: '-2.88690000',
            longitude: '29.12480000')
      ]),
      State(id: 3197, name: 'Gitega Province', stateCode: 'GI', cities: [
        City(
            id: 9767,
            name: 'Gitega',
            latitude: '-3.42708000',
            longitude: '29.92463000')
      ]),
      State(id: 3194, name: 'Karuzi Province', stateCode: 'KR', cities: [
        City(
            id: 9768,
            name: 'Karuzi',
            latitude: '-3.10139000',
            longitude: '30.16278000')
      ]),
      State(id: 3192, name: 'Kayanza Province', stateCode: 'KY', cities: [
        City(
            id: 9769,
            name: 'Kayanza',
            latitude: '-2.92210000',
            longitude: '29.62930000')
      ]),
      State(id: 3195, name: 'Kirundo Province', stateCode: 'KI', cities: [
        City(
            id: 9770,
            name: 'Kirundo',
            latitude: '-2.58450000',
            longitude: '30.09590000')
      ]),
      State(id: 3188, name: 'Makamba Province', stateCode: 'MA', cities: [
        City(
            id: 9771,
            name: 'Makamba',
            latitude: '-4.13480000',
            longitude: '29.80400000')
      ]),
      State(id: 3193, name: 'Muramvya Province', stateCode: 'MU', cities: [
        City(
            id: 9772,
            name: 'Muramvya',
            latitude: '-3.26820000',
            longitude: '29.60790000')
      ]),
      State(id: 3186, name: 'Muyinga Province', stateCode: 'MY', cities: [
        City(
            id: 9773,
            name: 'Muyinga',
            latitude: '-2.84510000',
            longitude: '30.34140000')
      ]),
      State(id: 3187, name: 'Mwaro Province', stateCode: 'MW', cities: [
        City(
            id: 9774,
            name: 'Mwaro',
            latitude: '-3.51128000',
            longitude: '29.70334000')
      ]),
      State(id: 3199, name: 'Ngozi Province', stateCode: 'NG', cities: [
        City(
            id: 9775,
            name: 'Ngozi',
            latitude: '-2.90750000',
            longitude: '29.83060000')
      ]),
      State(id: 3185, name: 'Rumonge Province', stateCode: 'RM', cities: [
        City(
            id: 9776,
            name: 'Rumonge',
            latitude: '-3.97360000',
            longitude: '29.43860000')
      ]),
      State(id: 3189, name: 'Rutana Province', stateCode: 'RT', cities: [
        City(
            id: 9777,
            name: 'Rutana',
            latitude: '-3.92790000',
            longitude: '29.99200000')
      ]),
      State(id: 3191, name: 'Ruyigi Province', stateCode: 'RY', cities: [
        City(
            id: 9778,
            name: 'Ruyigi',
            latitude: '-3.47639000',
            longitude: '30.24861000')
      ])
    ]);
