// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const dji = Country(
  id: 60,
  name: 'Djibouti',
  iso3: 'DJI',
  iso2: 'DJ',
  phoneCode: '253',
  capital: 'Djibouti',
  currency: 'DJF',
  currencySymbol: r'Fdj',
  tld: '.dj',
  native: 'Djibouti',
  region: 'Africa',
  subregion: 'Eastern Africa',
  timezones: [
    Timezone(
      zoneName: 'Africa/Djibouti',
      gmtOffset: 10800,
      gmtOffsetName: 'UTC+03:00',
      abbreviation: 'EAT',
      tzName: 'East Africa Time',
    )
  ],
  emoji: '🇩🇯',
  emojiU: 'U+1F1E9 U+1F1EF',
  states: [
    CountryState(
      id: 2933,
      name: 'Ali Sabieh Region',
      stateCode: 'AS',
      cities: [
        City(
          id: 30561,
          name: '\'Ali Sabieh',
          latitude: '11.15583000',
          longitude: '42.71250000',
        ),
        City(
          id: 30567,
          name: 'Goubétto',
          latitude: '11.42389000',
          longitude: '43.00028000',
        ),
        City(
          id: 30569,
          name: 'Holhol',
          latitude: '11.31028000',
          longitude: '42.92944000',
        ),
      ],
    ),
    CountryState(
      id: 2932,
      name: 'Arta Region',
      stateCode: 'AR',
      cities: [
        City(
          id: 30563,
          name: 'Arta',
          latitude: '11.52639000',
          longitude: '42.85194000',
        )
      ],
    ),
    CountryState(
      id: 2930,
      name: 'Dikhil Region',
      stateCode: 'DI',
      cities: [
        City(
          id: 30564,
          name: 'Dikhil',
          latitude: '11.10454000',
          longitude: '42.36971000',
        ),
        City(
          id: 30568,
          name: 'Gâlâfi',
          latitude: '11.71583000',
          longitude: '41.83611000',
        ),
      ],
    ),
    CountryState(
      id: 2929,
      name: 'Djibouti',
      stateCode: 'DJ',
      cities: [
        City(
          id: 30565,
          name: 'Djibouti',
          latitude: '11.58901000',
          longitude: '43.14503000',
        ),
        City(
          id: 30570,
          name: 'Loyada',
          latitude: '11.46111000',
          longitude: '43.25278000',
        ),
      ],
    ),
    CountryState(
      id: 2928,
      name: 'Obock Region',
      stateCode: 'OB',
      cities: [
        City(
          id: 30562,
          name: 'Alaïli Ḏaḏḏa‘',
          latitude: '12.42167000',
          longitude: '42.89556000',
        ),
        City(
          id: 30571,
          name: 'Obock',
          latitude: '11.96693000',
          longitude: '43.28835000',
        ),
      ],
    ),
    CountryState(
      id: 2931,
      name: 'Tadjourah Region',
      stateCode: 'TA',
      cities: [
        City(
          id: 30566,
          name: 'Dorra',
          latitude: '12.15028000',
          longitude: '42.47624000',
        ),
        City(
          id: 30572,
          name: 'Tadjourah',
          latitude: '11.78778000',
          longitude: '42.88222000',
        ),
      ],
    ),
  ],
);
