// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const atg = Country(
  id: 10,
  name: 'Antigua And Barbuda',
  iso3: 'ATG',
  iso2: 'AG',
  phoneCode: '+1-268',
  capital: 'St. John\'s',
  currency: 'XCD',
  currencySymbol: r'$',
  tld: '.ag',
  native: 'Antigua and Barbuda',
  region: 'Americas',
  subregion: 'Caribbean',
  timezones: [
    Timezone(
      zoneName: 'America/Antigua',
      gmtOffset: -14400,
      gmtOffsetName: 'UTC-04:00',
      abbreviation: 'AST',
      tzName: 'Atlantic Standard Time',
    )
  ],
  emoji: '🇦🇬',
  emojiU: 'U+1F1E6 U+1F1EC',
  states: [
    CountryState(
      id: 3708,
      name: 'Barbuda',
      stateCode: '10',
      cities: [
        City(
          id: 144,
          name: 'Codrington',
          latitude: '17.63333000',
          longitude: '-61.83333000',
        )
      ],
    ),
    CountryState(
      id: 3703,
      name: 'Redonda',
      stateCode: '11',
      cities: [],
    ),
    CountryState(
      id: 3709,
      name: 'Saint George Parish',
      stateCode: '03',
      cities: [
        City(
          id: 148,
          name: 'Piggotts',
          latitude: '17.11667000',
          longitude: '-61.80000000',
        )
      ],
    ),
    CountryState(
      id: 3706,
      name: 'Saint John Parish',
      stateCode: '04',
      cities: [
        City(
          id: 149,
          name: 'Potters Village',
          latitude: '17.11337000',
          longitude: '-61.81962000',
        ),
        City(
          id: 150,
          name: 'Saint John’s',
          latitude: '17.12096000',
          longitude: '-61.84329000',
        ),
      ],
    ),
    CountryState(
      id: 3707,
      name: 'Saint Mary Parish',
      stateCode: '05',
      cities: [
        City(
          id: 143,
          name: 'Bolands',
          latitude: '17.06565000',
          longitude: '-61.87466000',
        )
      ],
    ),
    CountryState(
      id: 3705,
      name: 'Saint Paul Parish',
      stateCode: '06',
      cities: [
        City(
          id: 145,
          name: 'Falmouth',
          latitude: '17.02741000',
          longitude: '-61.78136000',
        ),
        City(
          id: 146,
          name: 'Liberta',
          latitude: '17.04141000',
          longitude: '-61.79052000',
        ),
      ],
    ),
    CountryState(
      id: 3704,
      name: 'Saint Peter Parish',
      stateCode: '07',
      cities: [
        City(
          id: 142,
          name: 'All Saints',
          latitude: '17.06671000',
          longitude: '-61.79303000',
        ),
        City(
          id: 147,
          name: 'Parham',
          latitude: '17.09682000',
          longitude: '-61.77046000',
        ),
      ],
    ),
    CountryState(
      id: 3710,
      name: 'Saint Philip Parish',
      stateCode: '08',
      cities: [],
    ),
  ],
);
