// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const pyf = Country(
  id: 77,
  name: 'French Polynesia',
  iso3: 'PYF',
  iso2: 'PF',
  phoneCode: '689',
  capital: 'Papeete',
  currency: 'XPF',
  currencySymbol: r'₣',
  tld: '.pf',
  native: 'Polynésie française',
  region: 'Oceania',
  subregion: 'Polynesia',
  timezones: [
    Timezone(
      zoneName: 'Pacific/Gambier',
      gmtOffset: -32400,
      gmtOffsetName: 'UTC-09:00',
      abbreviation: 'GAMT',
      tzName: 'Gambier Islands Time',
    ),
    Timezone(
      zoneName: 'Pacific/Marquesas',
      gmtOffset: -34200,
      gmtOffsetName: 'UTC-09:30',
      abbreviation: 'MART',
      tzName: 'Marquesas Islands Time',
    ),
    Timezone(
      zoneName: 'Pacific/Tahiti',
      gmtOffset: -36000,
      gmtOffsetName: 'UTC-10:00',
      abbreviation: 'TAHT',
      tzName: 'Tahiti Time',
    ),
  ],
  emoji: '🇵🇫',
  emojiU: 'U+1F1F5 U+1F1EB',
  states: [],
);
