// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const jey = Country(
  id: 110,
  name: 'Jersey',
  iso3: 'JEY',
  iso2: 'JE',
  phoneCode: '+44-1534',
  capital: 'Saint Helier',
  currency: 'GBP',
  currencySymbol: r'£',
  tld: '.je',
  native: 'Jersey',
  region: 'Europe',
  subregion: 'Northern Europe',
  timezones: [
    Timezone(
      zoneName: 'Europe/Jersey',
      gmtOffset: 0,
      gmtOffsetName: 'UTC±00',
      abbreviation: 'GMT',
      tzName: 'Greenwich Mean Time',
    )
  ],
  emoji: '🇯🇪',
  emojiU: 'U+1F1EF U+1F1EA',
  states: [],
);
