// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const gab = Country(
    id: 79,
    name: 'Gabon',
    iso3: 'GAB',
    iso2: 'GA',
    phoneCode: '241',
    capital: 'Libreville',
    currency: 'XAF',
    currencySymbol: r'FCFA',
    tld: '.ga',
    native: 'Gabon',
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: [
      Timezone(
          zoneName: 'Africa/Libreville',
          gmtOffset: 3600,
          gmtOffsetName: 'UTC+01:00',
          abbreviation: 'WAT',
          tzName: 'West Africa Time')
    ],
    emoji: '🇬🇦',
    emojiU: 'U+1F1EC U+1F1E6',
    states: [
      State(id: 2727, name: 'Estuaire Province', stateCode: '1', cities: [
        City(
            id: 48131,
            name: 'Cocobeach',
            latitude: '1.00019000',
            longitude: '9.58229000'),
        City(
            id: 48138,
            name: 'Libreville',
            latitude: '0.39241000',
            longitude: '9.45356000'),
        City(
            id: 48150,
            name: 'Ntoum',
            latitude: '0.39051000',
            longitude: '9.76096000')
      ]),
      State(id: 2726, name: 'Haut-Ogooué Province', stateCode: '2', cities: [
        City(
            id: 48133,
            name: 'Franceville',
            latitude: '-1.63333000',
            longitude: '13.58357000'),
        City(
            id: 48139,
            name: 'Lékoni',
            latitude: '-1.58431000',
            longitude: '14.25905000'),
        City(
            id: 48145,
            name: 'Moanda',
            latitude: '-1.56652000',
            longitude: '13.19870000'),
        City(
            id: 48147,
            name: 'Mounana',
            latitude: '-1.40850000',
            longitude: '13.15857000'),
        City(
            id: 48151,
            name: 'Okondja',
            latitude: '-0.65487000',
            longitude: '13.67533000')
      ]),
      State(id: 2730, name: 'Moyen-Ogooué Province', stateCode: '3', cities: [
        City(
            id: 48136,
            name: 'Lambaréné',
            latitude: '-0.70010000',
            longitude: '10.24055000'),
        City(
            id: 48149,
            name: 'Ndjolé',
            latitude: '-0.17827000',
            longitude: '10.76488000')
      ]),
      State(id: 2731, name: 'Ngounié Province', stateCode: '4', cities: [
        City(
            id: 48132,
            name: 'Fougamou',
            latitude: '-1.21544000',
            longitude: '10.58378000'),
        City(
            id: 48142,
            name: 'Mbigou',
            latitude: '-1.90046000',
            longitude: '11.90600000'),
        City(
            id: 48143,
            name: 'Mimongo',
            latitude: '-1.61952000',
            longitude: '11.60675000'),
        City(
            id: 48146,
            name: 'Mouila',
            latitude: '-1.86846000',
            longitude: '11.05594000'),
        City(
            id: 48148,
            name: 'Ndendé',
            latitude: '-2.40077000',
            longitude: '11.35813000')
      ]),
      State(id: 2725, name: 'Nyanga Province', stateCode: '5', cities: [
        City(
            id: 48141,
            name: 'Mayumba',
            latitude: '-3.43198000',
            longitude: '10.65540000'),
        City(
            id: 48155,
            name: 'Tchibanga',
            latitude: '-2.93323000',
            longitude: '10.98178000')
      ]),
      State(id: 2724, name: 'Ogooué-Ivindo Province', stateCode: '6', cities: [
        City(
            id: 48130,
            name: 'Booué',
            latitude: '-0.09207000',
            longitude: '11.93846000'),
        City(
            id: 48140,
            name: 'Makokou',
            latitude: '0.57381000',
            longitude: '12.86419000'),
        City(
            id: 48156,
            name: 'Zadie',
            latitude: '0.92582000',
            longitude: '13.90813000')
      ]),
      State(id: 2729, name: 'Ogooué-Lolo Province', stateCode: '7', cities: [
        City(
            id: 48135,
            name: 'Koulamoutou',
            latitude: '-1.13667000',
            longitude: '12.46399000'),
        City(
            id: 48137,
            name: 'Lastoursville',
            latitude: '-0.81742000',
            longitude: '12.70818000')
      ]),
      State(
          id: 2728,
          name: 'Ogooué-Maritime Province',
          stateCode: '8',
          cities: [
            City(
                id: 48134,
                name: 'Gamba',
                latitude: '-2.65000000',
                longitude: '10.00000000'),
            City(
                id: 48152,
                name: 'Omboué',
                latitude: '-1.57464000',
                longitude: '9.26184000'),
            City(
                id: 48154,
                name: 'Port-Gentil',
                latitude: '-0.71933000',
                longitude: '8.78151000')
          ]),
      State(id: 2723, name: 'Woleu-Ntem Province', stateCode: '9', cities: [
        City(
            id: 48129,
            name: 'Bitam',
            latitude: '2.07597000',
            longitude: '11.50065000'),
        City(
            id: 48144,
            name: 'Mitzic',
            latitude: '0.78205000',
            longitude: '11.54904000'),
        City(
            id: 48153,
            name: 'Oyem',
            latitude: '1.59950000',
            longitude: '11.57933000')
      ])
    ]);
