// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const lva = Country(
  id: 120,
  name: 'Latvia',
  iso3: 'LVA',
  iso2: 'LV',
  phoneCode: '371',
  capital: 'Riga',
  currency: 'EUR',
  currencySymbol: r'€',
  tld: '.lv',
  native: 'Latvija',
  region: 'Europe',
  subregion: 'Northern Europe',
  timezones: [
    Timezone(
      zoneName: 'Europe/Riga',
      gmtOffset: 7200,
      gmtOffsetName: 'UTC+02:00',
      abbreviation: 'EET',
      tzName: 'Eastern European Time',
    )
  ],
  emoji: '🇱🇻',
  emojiU: 'U+1F1F1 U+1F1FB',
  states: [
    CountryState(
      id: 4445,
      name: 'Aglona Municipality',
      stateCode: '001',
      cities: [
        City(
          id: 66868,
          name: 'Aglona',
          latitude: '56.13274000',
          longitude: '27.00682000',
        )
      ],
    ),
    CountryState(
      id: 4472,
      name: 'Aizkraukle Municipality',
      stateCode: '002',
      cities: [
        City(
          id: 66870,
          name: 'Aizkraukle',
          latitude: '56.60477000',
          longitude: '25.25534000',
        )
      ],
    ),
    CountryState(
      id: 4496,
      name: 'Aizpute Municipality',
      stateCode: '003',
      cities: [
        City(
          id: 66871,
          name: 'Aizpute',
          latitude: '56.72108000',
          longitude: '21.60156000',
        )
      ],
    ),
    CountryState(
      id: 4499,
      name: 'Aknīste Municipality',
      stateCode: '004',
      cities: [
        City(
          id: 66872,
          name: 'Aknīste',
          latitude: '56.16152000',
          longitude: '25.74783000',
        )
      ],
    ),
    CountryState(
      id: 4484,
      name: 'Aloja Municipality',
      stateCode: '005',
      cities: [
        City(
          id: 66873,
          name: 'Aloja',
          latitude: '57.76723000',
          longitude: '24.87743000',
        ),
        City(
          id: 66966,
          name: 'Staicele',
          latitude: '57.83579000',
          longitude: '24.74706000',
        ),
      ],
    ),
    CountryState(
      id: 4485,
      name: 'Alsunga Municipality',
      stateCode: '006',
      cities: [
        City(
          id: 66874,
          name: 'Alsunga',
          latitude: '56.98194000',
          longitude: '21.55938000',
        )
      ],
    ),
    CountryState(
      id: 4487,
      name: 'Alūksne Municipality',
      stateCode: '007',
      cities: [
        City(
          id: 66875,
          name: 'Alūksne',
          latitude: '57.42162000',
          longitude: '27.04662000',
        )
      ],
    ),
    CountryState(
      id: 4497,
      name: 'Amata Municipality',
      stateCode: '008',
      cities: [],
    ),
    CountryState(
      id: 4457,
      name: 'Ape Municipality',
      stateCode: '009',
      cities: [
        City(
          id: 66876,
          name: 'Ape',
          latitude: '57.53928000',
          longitude: '26.69291000',
        )
      ],
    ),
    CountryState(
      id: 4481,
      name: 'Auce Municipality',
      stateCode: '010',
      cities: [
        City(
          id: 66877,
          name: 'Auce',
          latitude: '56.45981000',
          longitude: '22.90169000',
        )
      ],
    ),
    CountryState(
      id: 4427,
      name: 'Babīte Municipality',
      stateCode: '012',
      cities: [
        City(
          id: 66940,
          name: 'Piņķi',
          latitude: '56.94189000',
          longitude: '23.91365000',
        )
      ],
    ),
    CountryState(
      id: 4482,
      name: 'Baldone Municipality',
      stateCode: '013',
      cities: [
        City(
          id: 66878,
          name: 'Baldone',
          latitude: '56.74451000',
          longitude: '24.40078000',
        )
      ],
    ),
    CountryState(
      id: 4498,
      name: 'Baltinava Municipality',
      stateCode: '014',
      cities: [
        City(
          id: 66880,
          name: 'Baltinava',
          latitude: '56.94394000',
          longitude: '27.64401000',
        )
      ],
    ),
    CountryState(
      id: 4505,
      name: 'Balvi Municipality',
      stateCode: '015',
      cities: [
        City(
          id: 66881,
          name: 'Balvi',
          latitude: '57.13130000',
          longitude: '27.26583000',
        )
      ],
    ),
    CountryState(
      id: 4465,
      name: 'Bauska Municipality',
      stateCode: '016',
      cities: [
        City(
          id: 66882,
          name: 'Bauska',
          latitude: '56.40794000',
          longitude: '24.19443000',
        )
      ],
    ),
    CountryState(
      id: 4471,
      name: 'Beverīna Municipality',
      stateCode: '017',
      cities: [
        City(
          id: 66931,
          name: 'Mūrmuiža',
          latitude: '57.47312000',
          longitude: '25.49174000',
        )
      ],
    ),
    CountryState(
      id: 4468,
      name: 'Brocēni Municipality',
      stateCode: '018',
      cities: [
        City(
          id: 66884,
          name: 'Brocēni',
          latitude: '56.67890000',
          longitude: '22.56945000',
        )
      ],
    ),
    CountryState(
      id: 4411,
      name: 'Burtnieki Municipality',
      stateCode: '019',
      cities: [],
    ),
    CountryState(
      id: 4454,
      name: 'Carnikava Municipality',
      stateCode: '020',
      cities: [
        City(
          id: 66885,
          name: 'Carnikava',
          latitude: '57.12935000',
          longitude: '24.28423000',
        )
      ],
    ),
    CountryState(
      id: 4469,
      name: 'Cēsis Municipality',
      stateCode: '022',
      cities: [
        City(
          id: 66888,
          name: 'Cēsis',
          latitude: '57.31188000',
          longitude: '25.27456000',
        )
      ],
    ),
    CountryState(
      id: 4414,
      name: 'Cesvaine Municipality',
      stateCode: '021',
      cities: [
        City(
          id: 66886,
          name: 'Cesvaine',
          latitude: '56.96754000',
          longitude: '26.30764000',
        )
      ],
    ),
    CountryState(
      id: 4410,
      name: 'Cibla Municipality',
      stateCode: '023',
      cities: [
        City(
          id: 66887,
          name: 'Cibla',
          latitude: '56.54980000',
          longitude: '27.88370000',
        )
      ],
    ),
    CountryState(
      id: 4504,
      name: 'Dagda Municipality',
      stateCode: '024',
      cities: [
        City(
          id: 66889,
          name: 'Dagda',
          latitude: '56.09512000',
          longitude: '27.53723000',
        )
      ],
    ),
    CountryState(
      id: 4463,
      name: 'Daugavpils',
      stateCode: 'DGV',
      cities: [],
    ),
    CountryState(
      id: 4492,
      name: 'Daugavpils Municipality',
      stateCode: '025',
      cities: [
        City(
          id: 66891,
          name: 'Daugavpils',
          latitude: '55.88333000',
          longitude: '26.53333000',
        )
      ],
    ),
    CountryState(
      id: 4437,
      name: 'Dobele Municipality',
      stateCode: '026',
      cities: [
        City(
          id: 66892,
          name: 'Dobele',
          latitude: '56.62372000',
          longitude: '23.27510000',
        )
      ],
    ),
    CountryState(
      id: 4428,
      name: 'Dundaga Municipality',
      stateCode: '027',
      cities: [
        City(
          id: 66893,
          name: 'Dundaga',
          latitude: '57.50498000',
          longitude: '22.35041000',
        )
      ],
    ),
    CountryState(
      id: 4458,
      name: 'Durbe Municipality',
      stateCode: '028',
      cities: [
        City(
          id: 66920,
          name: 'Lieģi',
          latitude: '56.58173000',
          longitude: '21.33399000',
        )
      ],
    ),
    CountryState(
      id: 4448,
      name: 'Engure Municipality',
      stateCode: '029',
      cities: [
        City(
          id: 66965,
          name: 'Smārde',
          latitude: '56.95420000',
          longitude: '23.33736000',
        )
      ],
    ),
    CountryState(
      id: 4444,
      name: 'Ērgļi Municipality',
      stateCode: '030',
      cities: [
        City(
          id: 66990,
          name: 'Ērgļi',
          latitude: '56.89752000',
          longitude: '25.63668000',
        )
      ],
    ),
    CountryState(
      id: 4510,
      name: 'Garkalne Municipality',
      stateCode: '031',
      cities: [
        City(
          id: 66895,
          name: 'Garkalne',
          latitude: '57.04486000',
          longitude: '24.41951000',
        )
      ],
    ),
    CountryState(
      id: 4470,
      name: 'Grobiņa Municipality',
      stateCode: '032',
      cities: [
        City(
          id: 66896,
          name: 'Grobiņa',
          latitude: '56.53521000',
          longitude: '21.16782000',
        )
      ],
    ),
    CountryState(
      id: 4400,
      name: 'Gulbene Municipality',
      stateCode: '033',
      cities: [
        City(
          id: 66897,
          name: 'Gulbene',
          latitude: '57.17767000',
          longitude: '26.75291000',
        )
      ],
    ),
    CountryState(
      id: 4441,
      name: 'Iecava Municipality',
      stateCode: '034',
      cities: [
        City(
          id: 66898,
          name: 'Iecava',
          latitude: '56.59766000',
          longitude: '24.20763000',
        )
      ],
    ),
    CountryState(
      id: 4511,
      name: 'Ikšķile Municipality',
      stateCode: '035',
      cities: [
        City(
          id: 66899,
          name: 'Ikšķile',
          latitude: '56.83399000',
          longitude: '24.49679000',
        )
      ],
    ),
    CountryState(
      id: 4399,
      name: 'Ilūkste Municipality',
      stateCode: '036',
      cities: [
        City(
          id: 66900,
          name: 'Ilūkste',
          latitude: '55.97754000',
          longitude: '26.29655000',
        )
      ],
    ),
    CountryState(
      id: 4449,
      name: 'Inčukalns Municipality',
      stateCode: '037',
      cities: [
        City(
          id: 66901,
          name: 'Inčukalns',
          latitude: '57.09867000',
          longitude: '24.68630000',
        ),
        City(
          id: 66979,
          name: 'Vangaži',
          latitude: '57.09358000',
          longitude: '24.54468000',
        ),
      ],
    ),
    CountryState(
      id: 4475,
      name: 'Jaunjelgava Municipality',
      stateCode: '038',
      cities: [
        City(
          id: 66904,
          name: 'Jaunjelgava',
          latitude: '56.61319000',
          longitude: '25.08316000',
        )
      ],
    ),
    CountryState(
      id: 4407,
      name: 'Jaunpiebalga Municipality',
      stateCode: '039',
      cities: [],
    ),
    CountryState(
      id: 4489,
      name: 'Jaunpils Municipality',
      stateCode: '040',
      cities: [
        City(
          id: 66905,
          name: 'Jaunpils',
          latitude: '56.73137000',
          longitude: '23.01247000',
        )
      ],
    ),
    CountryState(
      id: 4464,
      name: 'Jēkabpils',
      stateCode: 'JKB',
      cities: [],
    ),
    CountryState(
      id: 4438,
      name: 'Jēkabpils Municipality',
      stateCode: '042',
      cities: [
        City(
          id: 66908,
          name: 'Jēkabpils',
          latitude: '56.49903000',
          longitude: '25.85735000',
        ),
        City(
          id: 66914,
          name: 'Krustpils',
          latitude: '56.51068000',
          longitude: '25.86117000',
        ),
      ],
    ),
    CountryState(
      id: 4500,
      name: 'Jelgava',
      stateCode: 'JEL',
      cities: [
        City(
          id: 66906,
          name: 'Jelgava',
          latitude: '56.65000000',
          longitude: '23.71278000',
        )
      ],
    ),
    CountryState(
      id: 4424,
      name: 'Jelgava Municipality',
      stateCode: '041',
      cities: [
        City(
          id: 66973,
          name: 'Tīreļi',
          latitude: '56.83991000',
          longitude: '23.58902000',
        )
      ],
    ),
    CountryState(
      id: 4446,
      name: 'Jūrmala',
      stateCode: 'JUR',
      cities: [
        City(
          id: 66909,
          name: 'Jūrmala',
          latitude: '56.96800000',
          longitude: '23.77038000',
        )
      ],
    ),
    CountryState(
      id: 4420,
      name: 'Kandava Municipality',
      stateCode: '043',
      cities: [
        City(
          id: 66910,
          name: 'Kandava',
          latitude: '57.04087000',
          longitude: '22.77466000',
        )
      ],
    ),
    CountryState(
      id: 4453,
      name: 'Kārsava Municipality',
      stateCode: '044',
      cities: [
        City(
          id: 66917,
          name: 'Kārsava',
          latitude: '56.78405000',
          longitude: '27.68829000',
        )
      ],
    ),
    CountryState(
      id: 4412,
      name: 'Ķegums Municipality',
      stateCode: '051',
      cities: [
        City(
          id: 66991,
          name: 'Ķegums',
          latitude: '56.74510000',
          longitude: '24.72439000',
        )
      ],
    ),
    CountryState(
      id: 4435,
      name: 'Ķekava Municipality',
      stateCode: '052',
      cities: [
        City(
          id: 66879,
          name: 'Baloži',
          latitude: '56.87643000',
          longitude: '24.11825000',
        ),
        City(
          id: 66992,
          name: 'Ķekava',
          latitude: '56.82662000',
          longitude: '24.23000000',
        ),
      ],
    ),
    CountryState(
      id: 4495,
      name: 'Kocēni Municipality',
      stateCode: '045',
      cities: [
        City(
          id: 66912,
          name: 'Kocēni',
          latitude: '57.52057000',
          longitude: '25.33821000',
        )
      ],
    ),
    CountryState(
      id: 4452,
      name: 'Koknese Municipality',
      stateCode: '046',
      cities: [
        City(
          id: 66913,
          name: 'Koknese',
          latitude: '56.65163000',
          longitude: '25.43637000',
        )
      ],
    ),
    CountryState(
      id: 4474,
      name: 'Krāslava Municipality',
      stateCode: '047',
      cities: [
        City(
          id: 66915,
          name: 'Krāslava',
          latitude: '55.89514000',
          longitude: '27.16799000',
        )
      ],
    ),
    CountryState(
      id: 4422,
      name: 'Krimulda Municipality',
      stateCode: '048',
      cities: [],
    ),
    CountryState(
      id: 4413,
      name: 'Krustpils Municipality',
      stateCode: '049',
      cities: [],
    ),
    CountryState(
      id: 4490,
      name: 'Kuldīga Municipality',
      stateCode: '050',
      cities: [
        City(
          id: 66916,
          name: 'Kuldīga',
          latitude: '56.97399000',
          longitude: '21.95721000',
        )
      ],
    ),
    CountryState(
      id: 4512,
      name: 'Lielvārde Municipality',
      stateCode: '053',
      cities: [
        City(
          id: 66918,
          name: 'Lielvārde',
          latitude: '56.72066000',
          longitude: '24.80743000',
        )
      ],
    ),
    CountryState(
      id: 4460,
      name: 'Liepāja',
      stateCode: 'LPX',
      cities: [
        City(
          id: 66911,
          name: 'Karosta',
          latitude: '56.55128000',
          longitude: '21.01287000',
        ),
        City(
          id: 66919,
          name: 'Liepāja',
          latitude: '56.50474000',
          longitude: '21.01085000',
        ),
      ],
    ),
    CountryState(
      id: 4488,
      name: 'Līgatne Municipality',
      stateCode: '055',
      cities: [
        City(
          id: 66924,
          name: 'Līgatne',
          latitude: '57.23429000',
          longitude: '25.04059000',
        )
      ],
    ),
    CountryState(
      id: 4418,
      name: 'Limbaži Municipality',
      stateCode: '054',
      cities: [
        City(
          id: 66921,
          name: 'Limbaži',
          latitude: '57.51287000',
          longitude: '24.71941000',
        )
      ],
    ),
    CountryState(
      id: 4401,
      name: 'Līvāni Municipality',
      stateCode: '056',
      cities: [
        City(
          id: 66925,
          name: 'Līvāni',
          latitude: '56.35431000',
          longitude: '26.17579000',
        )
      ],
    ),
    CountryState(
      id: 4419,
      name: 'Lubāna Municipality',
      stateCode: '057',
      cities: [
        City(
          id: 66922,
          name: 'Lubāna',
          latitude: '56.90425000',
          longitude: '26.71606000',
        )
      ],
    ),
    CountryState(
      id: 4501,
      name: 'Ludza Municipality',
      stateCode: '058',
      cities: [
        City(
          id: 66923,
          name: 'Ludza',
          latitude: '56.53958000',
          longitude: '27.71891000',
        )
      ],
    ),
    CountryState(
      id: 4433,
      name: 'Madona Municipality',
      stateCode: '059',
      cities: [
        City(
          id: 66926,
          name: 'Madona',
          latitude: '56.85329000',
          longitude: '26.21698000',
        )
      ],
    ),
    CountryState(
      id: 4461,
      name: 'Mālpils Municipality',
      stateCode: '061',
      cities: [
        City(
          id: 66929,
          name: 'Mālpils',
          latitude: '57.01010000',
          longitude: '24.95783000',
        )
      ],
    ),
    CountryState(
      id: 4450,
      name: 'Mārupe Municipality',
      stateCode: '062',
      cities: [
        City(
          id: 66930,
          name: 'Mārupe',
          latitude: '56.90544000',
          longitude: '24.05113000',
        )
      ],
    ),
    CountryState(
      id: 4513,
      name: 'Mazsalaca Municipality',
      stateCode: '060',
      cities: [
        City(
          id: 66927,
          name: 'Mazsalaca',
          latitude: '57.86329000',
          longitude: '25.05475000',
        )
      ],
    ),
    CountryState(
      id: 4451,
      name: 'Mērsrags Municipality',
      stateCode: '063',
      cities: [],
    ),
    CountryState(
      id: 4398,
      name: 'Naukšēni Municipality',
      stateCode: '064',
      cities: [
        City(
          id: 66932,
          name: 'Naukšēni',
          latitude: '57.88349000',
          longitude: '25.45609000',
        )
      ],
    ),
    CountryState(
      id: 4432,
      name: 'Nereta Municipality',
      stateCode: '065',
      cities: [
        City(
          id: 66933,
          name: 'Nereta',
          latitude: '56.20279000',
          longitude: '25.30752000',
        )
      ],
    ),
    CountryState(
      id: 4436,
      name: 'Nīca Municipality',
      stateCode: '066',
      cities: [
        City(
          id: 66934,
          name: 'Nīca',
          latitude: '56.34601000',
          longitude: '21.06401000',
        )
      ],
    ),
    CountryState(
      id: 4416,
      name: 'Ogre Municipality',
      stateCode: '067',
      cities: [
        City(
          id: 66907,
          name: 'Jumprava',
          latitude: '56.67613000',
          longitude: '24.97210000',
        ),
        City(
          id: 66935,
          name: 'Ogre',
          latitude: '56.81620000',
          longitude: '24.61401000',
        ),
      ],
    ),
    CountryState(
      id: 4417,
      name: 'Olaine Municipality',
      stateCode: '068',
      cities: [
        City(
          id: 66936,
          name: 'Olaine',
          latitude: '56.79472000',
          longitude: '23.93580000',
        )
      ],
    ),
    CountryState(
      id: 4442,
      name: 'Ozolnieki Municipality',
      stateCode: '069',
      cities: [
        City(
          id: 66937,
          name: 'Ozolnieki',
          latitude: '56.68986000',
          longitude: '23.77610000',
        )
      ],
    ),
    CountryState(
      id: 4507,
      name: 'Pārgauja Municipality',
      stateCode: '070',
      cities: [
        City(
          id: 66967,
          name: 'Stalbe',
          latitude: '57.37065000',
          longitude: '25.03106000',
        )
      ],
    ),
    CountryState(
      id: 4467,
      name: 'Pāvilosta Municipality',
      stateCode: '071',
      cities: [
        City(
          id: 66944,
          name: 'Pāvilosta',
          latitude: '56.88791000',
          longitude: '21.18593000',
        )
      ],
    ),
    CountryState(
      id: 4405,
      name: 'Pļaviņas Municipality',
      stateCode: '072',
      cities: [
        City(
          id: 66945,
          name: 'Pļaviņas',
          latitude: '56.61780000',
          longitude: '25.72552000',
        )
      ],
    ),
    CountryState(
      id: 4483,
      name: 'Preiļi Municipality',
      stateCode: '073',
      cities: [
        City(
          id: 66902,
          name: 'Jaunaglona',
          latitude: '56.16066000',
          longitude: '27.00714000',
        ),
        City(
          id: 66941,
          name: 'Preiļi',
          latitude: '56.29444000',
          longitude: '26.72459000',
        ),
      ],
    ),
    CountryState(
      id: 4429,
      name: 'Priekule Municipality',
      stateCode: '074',
      cities: [
        City(
          id: 66942,
          name: 'Priekule',
          latitude: '56.44679000',
          longitude: '21.58968000',
        )
      ],
    ),
    CountryState(
      id: 4506,
      name: 'Priekuļi Municipality',
      stateCode: '075',
      cities: [
        City(
          id: 66943,
          name: 'Priekuļi',
          latitude: '57.31500000',
          longitude: '25.36147000',
        )
      ],
    ),
    CountryState(
      id: 4479,
      name: 'Rauna Municipality',
      stateCode: '076',
      cities: [
        City(
          id: 66946,
          name: 'Rauna',
          latitude: '57.33173000',
          longitude: '25.60947000',
        )
      ],
    ),
    CountryState(
      id: 4509,
      name: 'Rēzekne',
      stateCode: 'REZ',
      cities: [
        City(
          id: 66953,
          name: 'Rēzekne',
          latitude: '56.51028000',
          longitude: '27.34000000',
        )
      ],
    ),
    CountryState(
      id: 4455,
      name: 'Rēzekne Municipality',
      stateCode: '077',
      cities: [],
    ),
    CountryState(
      id: 4502,
      name: 'Riebiņi Municipality',
      stateCode: '078',
      cities: [
        City(
          id: 66947,
          name: 'Riebiņi',
          latitude: '56.34280000',
          longitude: '26.79995000',
        )
      ],
    ),
    CountryState(
      id: 4491,
      name: 'Riga',
      stateCode: 'RIX',
      cities: [
        City(
          id: 66883,
          name: 'Bolderaja',
          latitude: '57.03132000',
          longitude: '24.05571000',
        ),
        City(
          id: 66890,
          name: 'Daugavgrīva',
          latitude: '57.04315000',
          longitude: '24.03613000',
        ),
        City(
          id: 66903,
          name: 'Jaunciems',
          latitude: '57.03910000',
          longitude: '24.17413000',
        ),
        City(
          id: 66928,
          name: 'Mežaparks',
          latitude: '57.00008000',
          longitude: '24.15997000',
        ),
        City(
          id: 66948,
          name: 'Riga',
          latitude: '56.94600000',
          longitude: '24.10589000',
        ),
      ],
    ),
    CountryState(
      id: 4440,
      name: 'Roja Municipality',
      stateCode: '079',
      cities: [
        City(
          id: 66949,
          name: 'Roja',
          latitude: '57.50146000',
          longitude: '22.80881000',
        )
      ],
    ),
    CountryState(
      id: 4493,
      name: 'Ropaži Municipality',
      stateCode: '080',
      cities: [
        City(
          id: 66950,
          name: 'Ropaži',
          latitude: '56.97470000',
          longitude: '24.63295000',
        )
      ],
    ),
    CountryState(
      id: 4503,
      name: 'Rucava Municipality',
      stateCode: '081',
      cities: [
        City(
          id: 66951,
          name: 'Rucava',
          latitude: '56.16314000',
          longitude: '21.16156000',
        )
      ],
    ),
    CountryState(
      id: 4423,
      name: 'Rugāji Municipality',
      stateCode: '082',
      cities: [
        City(
          id: 66952,
          name: 'Rugāji',
          latitude: '57.00325000',
          longitude: '27.13371000',
        )
      ],
    ),
    CountryState(
      id: 4426,
      name: 'Rūjiena Municipality',
      stateCode: '084',
      cities: [
        City(
          id: 66954,
          name: 'Rūjiena',
          latitude: '57.89752000',
          longitude: '25.33155000',
        )
      ],
    ),
    CountryState(
      id: 4404,
      name: 'Rundāle Municipality',
      stateCode: '083',
      cities: [
        City(
          id: 66938,
          name: 'Pilsrundāle',
          latitude: '56.41812000',
          longitude: '24.01625000',
        )
      ],
    ),
    CountryState(
      id: 4434,
      name: 'Sala Municipality',
      stateCode: '085',
      cities: [],
    ),
    CountryState(
      id: 4396,
      name: 'Salacgrīva Municipality',
      stateCode: '086',
      cities: [
        City(
          id: 66869,
          name: 'Ainaži',
          latitude: '57.86348000',
          longitude: '24.35853000',
        ),
        City(
          id: 66956,
          name: 'Salacgrīva',
          latitude: '57.75312000',
          longitude: '24.35895000',
        ),
      ],
    ),
    CountryState(
      id: 4402,
      name: 'Salaspils Municipality',
      stateCode: '087',
      cities: [
        City(
          id: 66957,
          name: 'Salaspils',
          latitude: '56.86014000',
          longitude: '24.36544000',
        )
      ],
    ),
    CountryState(
      id: 4439,
      name: 'Saldus Municipality',
      stateCode: '088',
      cities: [
        City(
          id: 66958,
          name: 'Saldus',
          latitude: '56.66363000',
          longitude: '22.48807000',
        )
      ],
    ),
    CountryState(
      id: 4443,
      name: 'Saulkrasti Municipality',
      stateCode: '089',
      cities: [
        City(
          id: 66959,
          name: 'Saulkrasti',
          latitude: '57.26224000',
          longitude: '24.41471000',
        )
      ],
    ),
    CountryState(
      id: 4408,
      name: 'Sēja Municipality',
      stateCode: '090',
      cities: [
        City(
          id: 66894,
          name: 'Engure',
          latitude: '57.16061000',
          longitude: '23.22527000',
        ),
        City(
          id: 66971,
          name: 'Tukums',
          latitude: '56.96764000',
          longitude: '23.15554000',
        ),
      ],
    ),
    CountryState(
      id: 4476,
      name: 'Sigulda Municipality',
      stateCode: '091',
      cities: [
        City(
          id: 66961,
          name: 'Sigulda',
          latitude: '57.15375000',
          longitude: '24.85953000',
        )
      ],
    ),
    CountryState(
      id: 4415,
      name: 'Skrīveri Municipality',
      stateCode: '092',
      cities: [
        City(
          id: 66963,
          name: 'Skrīveri',
          latitude: '56.64500000',
          longitude: '25.12058000',
        )
      ],
    ),
    CountryState(
      id: 4447,
      name: 'Skrunda Municipality',
      stateCode: '093',
      cities: [
        City(
          id: 66962,
          name: 'Skrunda',
          latitude: '56.67749000',
          longitude: '22.01649000',
        )
      ],
    ),
    CountryState(
      id: 4462,
      name: 'Smiltene Municipality',
      stateCode: '094',
      cities: [
        City(
          id: 66964,
          name: 'Smiltene',
          latitude: '57.42444000',
          longitude: '25.90164000',
        )
      ],
    ),
    CountryState(
      id: 4478,
      name: 'Stopiņi Municipality',
      stateCode: '095',
      cities: [
        City(
          id: 66974,
          name: 'Ulbroka',
          latitude: '56.93630000',
          longitude: '24.30387000',
        )
      ],
    ),
    CountryState(
      id: 4494,
      name: 'Strenči Municipality',
      stateCode: '096',
      cities: [
        City(
          id: 66960,
          name: 'Seda',
          latitude: '57.65042000',
          longitude: '25.75089000',
        ),
        City(
          id: 66969,
          name: 'Strenči',
          latitude: '57.62574000',
          longitude: '25.68535000',
        ),
      ],
    ),
    CountryState(
      id: 4459,
      name: 'Talsi Municipality',
      stateCode: '097',
      cities: [
        City(
          id: 66955,
          name: 'Sabile',
          latitude: '57.04577000',
          longitude: '22.57261000',
        ),
        City(
          id: 66968,
          name: 'Stende',
          latitude: '57.14497000',
          longitude: '22.53482000',
        ),
        City(
          id: 66970,
          name: 'Talsi',
          latitude: '57.24562000',
          longitude: '22.58137000',
        ),
        City(
          id: 66976,
          name: 'Valdemārpils',
          latitude: '57.37068000',
          longitude: '22.59188000',
        ),
      ],
    ),
    CountryState(
      id: 4480,
      name: 'Tērvete Municipality',
      stateCode: '098',
      cities: [
        City(
          id: 66972,
          name: 'Tērvete',
          latitude: '56.47989000',
          longitude: '23.38895000',
        ),
        City(
          id: 66988,
          name: 'Zelmeņi',
          latitude: '56.45167000',
          longitude: '23.35194000',
        ),
      ],
    ),
    CountryState(
      id: 4409,
      name: 'Tukums Municipality',
      stateCode: '099',
      cities: [],
    ),
    CountryState(
      id: 4508,
      name: 'Vaiņode Municipality',
      stateCode: '100',
      cities: [
        City(
          id: 66975,
          name: 'Vaiņode',
          latitude: '56.41848000',
          longitude: '21.85405000',
        )
      ],
    ),
    CountryState(
      id: 4425,
      name: 'Valka Municipality',
      stateCode: '101',
      cities: [
        City(
          id: 66977,
          name: 'Valka',
          latitude: '57.77520000',
          longitude: '26.01013000',
        )
      ],
    ),
    CountryState(
      id: 4473,
      name: 'Valmiera',
      stateCode: 'VMR',
      cities: [
        City(
          id: 66978,
          name: 'Valmiera',
          latitude: '57.54108000',
          longitude: '25.42751000',
        )
      ],
    ),
    CountryState(
      id: 4431,
      name: 'Varakļāni Municipality',
      stateCode: '102',
      cities: [
        City(
          id: 66980,
          name: 'Varakļāni',
          latitude: '56.60826000',
          longitude: '26.75377000',
        )
      ],
    ),
    CountryState(
      id: 4406,
      name: 'Vārkava Municipality',
      stateCode: '103',
      cities: [
        City(
          id: 66983,
          name: 'Vecvārkava',
          latitude: '56.19838000',
          longitude: '26.50811000',
        )
      ],
    ),
    CountryState(
      id: 4466,
      name: 'Vecpiebalga Municipality',
      stateCode: '104',
      cities: [
        City(
          id: 66981,
          name: 'Vecpiebalga',
          latitude: '57.06090000',
          longitude: '25.81624000',
        )
      ],
    ),
    CountryState(
      id: 4397,
      name: 'Vecumnieki Municipality',
      stateCode: '105',
      cities: [
        City(
          id: 66982,
          name: 'Vecumnieki',
          latitude: '56.60608000',
          longitude: '24.52232000',
        )
      ],
    ),
    CountryState(
      id: 4421,
      name: 'Ventspils',
      stateCode: 'VEN',
      cities: [
        City(
          id: 66984,
          name: 'Ventspils',
          latitude: '57.38988000',
          longitude: '21.57288000',
        )
      ],
    ),
    CountryState(
      id: 4403,
      name: 'Ventspils Municipality',
      stateCode: '106',
      cities: [
        City(
          id: 66939,
          name: 'Piltene',
          latitude: '57.22426000',
          longitude: '21.67439000',
        )
      ],
    ),
    CountryState(
      id: 4456,
      name: 'Viesīte Municipality',
      stateCode: '107',
      cities: [
        City(
          id: 66985,
          name: 'Viesīte',
          latitude: '56.34751000',
          longitude: '25.55514000',
        )
      ],
    ),
    CountryState(
      id: 4477,
      name: 'Viļaka Municipality',
      stateCode: '108',
      cities: [
        City(
          id: 66986,
          name: 'Viļaka',
          latitude: '57.18458000',
          longitude: '27.67220000',
        )
      ],
    ),
    CountryState(
      id: 4486,
      name: 'Viļāni Municipality',
      stateCode: '109',
      cities: [
        City(
          id: 66987,
          name: 'Viļāni',
          latitude: '56.55253000',
          longitude: '26.92449000',
        )
      ],
    ),
    CountryState(
      id: 4430,
      name: 'Zilupe Municipality',
      stateCode: '110',
      cities: [
        City(
          id: 66989,
          name: 'Zilupe',
          latitude: '56.38616000',
          longitude: '28.12165000',
        )
      ],
    ),
  ],
);
