// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const fji = Country(
    id: 73,
    name: 'Fiji Islands',
    iso3: 'FJI',
    iso2: 'FJ',
    phoneCode: '679',
    capital: 'Suva',
    currency: 'FJD',
    currencySymbol: r'FJ$',
    tld: '.fj',
    native: 'Fiji',
    region: 'Oceania',
    subregion: 'Melanesia',
    timezones: [
      Timezone(
          zoneName: 'Pacific/Fiji',
          gmtOffset: 43200,
          gmtOffsetName: 'UTC+12:00',
          abbreviation: 'FJT',
          tzName: 'Fiji Time')
    ],
    emoji: '🇫🇯',
    emojiU: 'U+1F1EB U+1F1EF',
    states: [
      State(id: 1917, name: 'Ba', stateCode: '01', cities: []),
      State(id: 1930, name: 'Bua', stateCode: '02', cities: []),
      State(id: 1924, name: 'Cakaudrove', stateCode: '03', cities: []),
      State(id: 1929, name: 'Central Division', stateCode: 'C', cities: [
        City(
            id: 39145,
            name: 'Naitasiri Province',
            latitude: '-17.83333000',
            longitude: '178.25000000'),
        City(
            id: 39146,
            name: 'Namosi Province',
            latitude: '-18.05000000',
            longitude: '178.13333000'),
        City(
            id: 39149,
            name: 'Rewa Province',
            latitude: '-18.08333000',
            longitude: '178.33333000'),
        City(
            id: 39150,
            name: 'Serua Province',
            latitude: '-18.16667000',
            longitude: '178.00000000'),
        City(
            id: 39151,
            name: 'Suva',
            latitude: '-18.14161000',
            longitude: '178.44149000'),
        City(
            id: 39152,
            name: 'Tailevu Province',
            latitude: '-17.83333000',
            longitude: '178.50000000')
      ]),
      State(id: 1932, name: 'Eastern Division', stateCode: 'E', cities: [
        City(
            id: 39137,
            name: 'Kadavu Province',
            latitude: '-18.99331000',
            longitude: '178.22021000'),
        City(
            id: 39139,
            name: 'Lau Province',
            latitude: '-18.20488000',
            longitude: '-178.79251000'),
        City(
            id: 39141,
            name: 'Levuka',
            latitude: '-18.06667000',
            longitude: '179.31667000'),
        City(
            id: 39142,
            name: 'Lomaiviti Province',
            latitude: '-17.66667000',
            longitude: '178.80000000')
      ]),
      State(id: 1934, name: 'Kadavu', stateCode: '04', cities: []),
      State(id: 1933, name: 'Lau', stateCode: '05', cities: []),
      State(id: 1916, name: 'Lomaiviti', stateCode: '06', cities: []),
      State(id: 1922, name: 'Macuata', stateCode: '07', cities: []),
      State(id: 1919, name: 'Nadroga-Navosa', stateCode: '08', cities: []),
      State(id: 1927, name: 'Naitasiri', stateCode: '09', cities: []),
      State(id: 1928, name: 'Namosi', stateCode: '10', cities: []),
      State(id: 1921, name: 'Northern Division', stateCode: 'N', cities: [
        City(
            id: 39135,
            name: 'Bua Province',
            latitude: '-16.83333000',
            longitude: '178.75000000'),
        City(
            id: 39136,
            name: 'Cakaudrove Province',
            latitude: '-16.66667000',
            longitude: '179.41667000'),
        City(
            id: 39138,
            name: 'Labasa',
            latitude: '-16.43320000',
            longitude: '179.36451000'),
        City(
            id: 39143,
            name: 'Macuata Province',
            latitude: '-16.50000000',
            longitude: '179.25000000')
      ]),
      State(id: 1926, name: 'Ra', stateCode: '11', cities: []),
      State(id: 1920, name: 'Rewa', stateCode: '12', cities: []),
      State(id: 1931, name: 'Rotuma', stateCode: 'R', cities: []),
      State(id: 1925, name: 'Serua', stateCode: '13', cities: []),
      State(id: 1918, name: 'Tailevu', stateCode: '14', cities: []),
      State(id: 1923, name: 'Western Division', stateCode: 'W', cities: [
        City(
            id: 39133,
            name: 'Ba',
            latitude: '-17.53430000',
            longitude: '177.67407000'),
        City(
            id: 39134,
            name: 'Ba Province',
            latitude: '-17.66667000',
            longitude: '177.66667000'),
        City(
            id: 39140,
            name: 'Lautoka',
            latitude: '-17.61686000',
            longitude: '177.45049000'),
        City(
            id: 39144,
            name: 'Nadi',
            latitude: '-17.80309000',
            longitude: '177.41617000'),
        City(
            id: 39147,
            name: 'Nandronga and Navosa Province',
            latitude: '-18.00000000',
            longitude: '177.66667000'),
        City(
            id: 39148,
            name: 'Ra Province',
            latitude: '-17.50000000',
            longitude: '178.16667000')
      ])
    ]);
