// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const tca = Country(
    id: 227,
    name: 'Turks And Caicos Islands',
    iso3: 'TCA',
    iso2: 'TC',
    phoneCode: '+1-649',
    capital: 'Cockburn Town',
    currency: 'USD',
    currencySymbol: r'$',
    tld: '.tc',
    native: 'Turks and Caicos Islands',
    region: 'Americas',
    subregion: 'Caribbean',
    timezones: [
      Timezone(
          zoneName: 'America/Grand_Turk',
          gmtOffset: -18000,
          gmtOffsetName: 'UTC-05:00',
          abbreviation: 'EST',
          tzName: 'Eastern Standard Time (North America')
    ],
    emoji: '🇹🇨',
    emojiU: 'U+1F1F9 U+1F1E8',
    states: []);
