// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const cog = Country(
    id: 50,
    name: 'Congo',
    iso3: 'COG',
    iso2: 'CG',
    phoneCode: '242',
    capital: 'Brazzaville',
    currency: 'XAF',
    currencySymbol: r'FC',
    tld: '.cg',
    native: 'République du Congo',
    region: 'Africa',
    subregion: 'Middle Africa',
    timezones: [
      Timezone(
          zoneName: 'Africa/Brazzaville',
          gmtOffset: 3600,
          gmtOffsetName: 'UTC+01:00',
          abbreviation: 'WAT',
          tzName: 'West Africa Time')
    ],
    emoji: '🇨🇬',
    emojiU: 'U+1F1E8 U+1F1EC',
    states: [
      State(id: 2866, name: 'Bouenza Department', stateCode: '11', cities: [
        City(
            id: 17345,
            name: 'Kayes',
            latitude: '-4.20493000',
            longitude: '13.28608000'),
        City(
            id: 17348,
            name: 'Madingou',
            latitude: '-4.15361000',
            longitude: '13.55000000')
      ]),
      State(id: 2870, name: 'Brazzaville', stateCode: 'BZV', cities: [
        City(
            id: 17339,
            name: 'Brazzaville',
            latitude: '-4.26613000',
            longitude: '15.28318000')
      ]),
      State(id: 2864, name: 'Cuvette Department', stateCode: '8', cities: [
        City(
            id: 17349,
            name: 'Makoua',
            latitude: '0.00694000',
            longitude: '15.63333000'),
        City(
            id: 17352,
            name: 'Owando',
            latitude: '-0.48193000',
            longitude: '15.89988000')
      ]),
      State(
          id: 2869,
          name: 'Cuvette-Ouest Department',
          stateCode: '15',
          cities: [
            City(
                id: 17342,
                name: 'Ewo',
                latitude: '-0.87250000',
                longitude: '14.82056000')
          ]),
      State(id: 2867, name: 'Kouilou Department', stateCode: '5', cities: []),
      State(id: 2868, name: 'Lékoumou Department', stateCode: '2', cities: [
        City(
            id: 17354,
            name: 'Sibiti',
            latitude: '-3.68192000',
            longitude: '13.34985000')
      ]),
      State(id: 2865, name: 'Likouala Department', stateCode: '7', cities: [
        City(
            id: 17344,
            name: 'Impfondo',
            latitude: '1.61804000',
            longitude: '18.05981000')
      ]),
      State(id: 2872, name: 'Niari Department', stateCode: '9', cities: [
        City(
            id: 17341,
            name: 'Dolisie',
            latitude: '-4.19834000',
            longitude: '12.66664000'),
        City(
            id: 17350,
            name: 'Mossendjo',
            latitude: '-2.94968000',
            longitude: '12.70423000')
      ]),
      State(id: 2862, name: 'Plateaux Department', stateCode: '14', cities: [
        City(
            id: 17340,
            name: 'Djambala',
            latitude: '-2.54472000',
            longitude: '14.75333000'),
        City(
            id: 17343,
            name: 'Gamboma',
            latitude: '-1.87639000',
            longitude: '15.86444000')
      ]),
      State(id: 2863, name: 'Pointe-Noire', stateCode: '16', cities: [
        City(
            id: 17347,
            name: 'Loandjili',
            latitude: '-4.75611000',
            longitude: '11.85778000'),
        City(
            id: 17353,
            name: 'Pointe-Noire',
            latitude: '-4.77609000',
            longitude: '11.86352000')
      ]),
      State(id: 2873, name: 'Pool Department', stateCode: '12', cities: [
        City(
            id: 17346,
            name: 'Kinkala',
            latitude: '-4.36139000',
            longitude: '14.76444000')
      ]),
      State(id: 2871, name: 'Sangha Department', stateCode: '13', cities: [
        City(
            id: 17351,
            name: 'Ouésso',
            latitude: '1.61361000',
            longitude: '16.05167000'),
        City(
            id: 17355,
            name: 'Sémbé',
            latitude: '1.64806000',
            longitude: '14.58056000')
      ])
    ]);
