// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const ata = Country(
    id: 9,
    name: 'Antarctica',
    iso3: 'ATA',
    iso2: 'AQ',
    phoneCode: '',
    capital: '',
    currency: '',
    currencySymbol: r'$',
    tld: '.aq',
    native: 'Antarctica',
    region: 'Polar',
    subregion: '',
    timezones: [
      Timezone(
          zoneName: 'Antarctica/Casey',
          gmtOffset: 39600,
          gmtOffsetName: 'UTC+11:00',
          abbreviation: 'AWST',
          tzName: 'Australian Western Standard Time'),
      Timezone(
          zoneName: 'Antarctica/Davis',
          gmtOffset: 25200,
          gmtOffsetName: 'UTC+07:00',
          abbreviation: 'DAVT',
          tzName: 'Davis Time'),
      Timezone(
          zoneName: 'Antarctica/DumontDUrville',
          gmtOffset: 36000,
          gmtOffsetName: 'UTC+10:00',
          abbreviation: 'DDUT',
          tzName: 'Dumont d\'Urville Time'),
      Timezone(
          zoneName: 'Antarctica/Mawson',
          gmtOffset: 18000,
          gmtOffsetName: 'UTC+05:00',
          abbreviation: 'MAWT',
          tzName: 'Mawson Station Time'),
      Timezone(
          zoneName: 'Antarctica/McMurdo',
          gmtOffset: 46800,
          gmtOffsetName: 'UTC+13:00',
          abbreviation: 'NZDT',
          tzName: 'New Zealand Daylight Time'),
      Timezone(
          zoneName: 'Antarctica/Palmer',
          gmtOffset: -10800,
          gmtOffsetName: 'UTC-03:00',
          abbreviation: 'CLST',
          tzName: 'Chile Summer Time'),
      Timezone(
          zoneName: 'Antarctica/Rothera',
          gmtOffset: -10800,
          gmtOffsetName: 'UTC-03:00',
          abbreviation: 'ROTT',
          tzName: 'Rothera Research Station Time'),
      Timezone(
          zoneName: 'Antarctica/Syowa',
          gmtOffset: 10800,
          gmtOffsetName: 'UTC+03:00',
          abbreviation: 'SYOT',
          tzName: 'Showa Station Time'),
      Timezone(
          zoneName: 'Antarctica/Troll',
          gmtOffset: 0,
          gmtOffsetName: 'UTC±00',
          abbreviation: 'GMT',
          tzName: 'Greenwich Mean Time'),
      Timezone(
          zoneName: 'Antarctica/Vostok',
          gmtOffset: 21600,
          gmtOffsetName: 'UTC+06:00',
          abbreviation: 'VOST',
          tzName: 'Vostok Station Time')
    ],
    emoji: '🇦🇶',
    emojiU: 'U+1F1E6 U+1F1F6',
    states: []);
