// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const tgo = Country(
  id: 220,
  name: 'Togo',
  iso3: 'TGO',
  iso2: 'TG',
  phoneCode: '228',
  capital: 'Lome',
  currency: 'XOF',
  currencySymbol: r'CFA',
  tld: '.tg',
  native: 'Togo',
  region: 'Africa',
  subregion: 'Western Africa',
  timezones: [
    Timezone(
      zoneName: 'Africa/Lome',
      gmtOffset: 0,
      gmtOffsetName: 'UTC±00',
      abbreviation: 'GMT',
      tzName: 'Greenwich Mean Time',
    )
  ],
  emoji: '🇹🇬',
  emojiU: 'U+1F1F9 U+1F1EC',
  states: [
    CountryState(
      id: 2575,
      name: 'Centrale Region',
      stateCode: 'C',
      cities: [
        City(
          id: 105173,
          name: 'Sokodé',
          latitude: '8.98333000',
          longitude: '1.13333000',
        ),
        City(
          id: 105174,
          name: 'Sotouboua',
          latitude: '8.56340000',
          longitude: '0.98399000',
        ),
        City(
          id: 105176,
          name: 'Tchamba',
          latitude: '9.03333000',
          longitude: '1.41667000',
        ),
      ],
    ),
    CountryState(
      id: 2579,
      name: 'Kara Region',
      stateCode: 'K',
      cities: [
        City(
          id: 105161,
          name: 'Bafilo',
          latitude: '9.35000000',
          longitude: '1.26667000',
        ),
        City(
          id: 105162,
          name: 'Bassar',
          latitude: '9.25025000',
          longitude: '0.78213000',
        ),
        City(
          id: 105164,
          name: 'Kandé',
          latitude: '9.95778000',
          longitude: '1.04472000',
        ),
        City(
          id: 105165,
          name: 'Kara',
          latitude: '9.55111000',
          longitude: '1.18611000',
        ),
        City(
          id: 105168,
          name: 'Niamtougou',
          latitude: '9.76806000',
          longitude: '1.10528000',
        ),
        City(
          id: 105170,
          name: 'Pagouda',
          latitude: '9.75250000',
          longitude: '1.32778000',
        ),
        City(
          id: 105171,
          name: 'Préfecture de Bassar',
          latitude: '9.25000000',
          longitude: '0.75000000',
        ),
      ],
    ),
    CountryState(
      id: 2576,
      name: 'Maritime',
      stateCode: 'M',
      cities: [
        City(
          id: 105158,
          name: 'Aného',
          latitude: '6.22798000',
          longitude: '1.59190000',
        ),
        City(
          id: 105167,
          name: 'Lomé',
          latitude: '6.12874000',
          longitude: '1.22154000',
        ),
        City(
          id: 105175,
          name: 'Tabligbo',
          latitude: '6.58333000',
          longitude: '1.50000000',
        ),
        City(
          id: 105177,
          name: 'Tsévié',
          latitude: '6.42611000',
          longitude: '1.21333000',
        ),
        City(
          id: 105178,
          name: 'Vogan',
          latitude: '6.33333000',
          longitude: '1.53333000',
        ),
      ],
    ),
    CountryState(
      id: 2577,
      name: 'Plateaux Region',
      stateCode: 'P',
      cities: [
        City(
          id: 105157,
          name: 'Amlamé',
          latitude: '7.46667000',
          longitude: '0.90000000',
        ),
        City(
          id: 105159,
          name: 'Atakpamé',
          latitude: '7.53333000',
          longitude: '1.13333000',
        ),
        City(
          id: 105160,
          name: 'Badou',
          latitude: '7.58333000',
          longitude: '0.60000000',
        ),
        City(
          id: 105166,
          name: 'Kpalimé',
          latitude: '6.90000000',
          longitude: '0.63333000',
        ),
        City(
          id: 105169,
          name: 'Notsé',
          latitude: '6.95000000',
          longitude: '1.16667000',
        ),
      ],
    ),
    CountryState(
      id: 2578,
      name: 'Savanes Region',
      stateCode: 'S',
      cities: [
        City(
          id: 105163,
          name: 'Dapaong',
          latitude: '10.86225000',
          longitude: '0.20762000',
        ),
        City(
          id: 105172,
          name: 'Sansanné-Mango',
          latitude: '10.35917000',
          longitude: '0.47083000',
        ),
      ],
    ),
  ],
);
