// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const slb = Country(
  id: 202,
  name: 'Solomon Islands',
  iso3: 'SLB',
  iso2: 'SB',
  phoneCode: '677',
  capital: 'Honiara',
  currency: 'SBD',
  currencySymbol: r'Si$',
  tld: '.sb',
  native: 'Solomon Islands',
  region: 'Oceania',
  subregion: 'Melanesia',
  timezones: [
    Timezone(
      zoneName: 'Pacific/Guadalcanal',
      gmtOffset: 39600,
      gmtOffsetName: 'UTC+11:00',
      abbreviation: 'SBT',
      tzName: 'Solomon Islands Time',
    )
  ],
  emoji: '🇸🇧',
  emojiU: 'U+1F1F8 U+1F1E7',
  states: [
    CountryState(
      id: 4784,
      name: 'Central Province',
      stateCode: 'CE',
      cities: [
        City(
          id: 102905,
          name: 'Tulagi',
          latitude: '-9.10306000',
          longitude: '160.15056000',
        )
      ],
    ),
    CountryState(
      id: 4781,
      name: 'Choiseul Province',
      stateCode: 'CH',
      cities: [],
    ),
    CountryState(
      id: 4785,
      name: 'Guadalcanal Province',
      stateCode: 'GU',
      cities: [
        City(
          id: 102902,
          name: 'Honiara',
          latitude: '-9.43333000',
          longitude: '159.95000000',
        )
      ],
    ),
    CountryState(
      id: 4778,
      name: 'Honiara',
      stateCode: 'CT',
      cities: [],
    ),
    CountryState(
      id: 4780,
      name: 'Isabel Province',
      stateCode: 'IS',
      cities: [
        City(
          id: 102900,
          name: 'Buala',
          latitude: '-8.14497000',
          longitude: '159.59212000',
        )
      ],
    ),
    CountryState(
      id: 4782,
      name: 'Makira-Ulawa Province',
      stateCode: 'MK',
      cities: [
        City(
          id: 102903,
          name: 'Kirakira',
          latitude: '-10.45442000',
          longitude: '161.92045000',
        )
      ],
    ),
    CountryState(
      id: 4783,
      name: 'Malaita Province',
      stateCode: 'ML',
      cities: [
        City(
          id: 102899,
          name: 'Auki',
          latitude: '-8.76778000',
          longitude: '160.69778000',
        )
      ],
    ),
    CountryState(
      id: 4787,
      name: 'Rennell and Bellona Province',
      stateCode: 'RB',
      cities: [],
    ),
    CountryState(
      id: 4779,
      name: 'Temotu Province',
      stateCode: 'TE',
      cities: [
        City(
          id: 102904,
          name: 'Lata',
          latitude: '-10.72500000',
          longitude: '165.79722000',
        )
      ],
    ),
    CountryState(
      id: 4786,
      name: 'Western Province',
      stateCode: 'WE',
      cities: [
        City(
          id: 102901,
          name: 'Gizo',
          latitude: '-8.10303000',
          longitude: '156.84186000',
        )
      ],
    ),
  ],
);
