// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const wlf = Country(
    id: 243,
    name: 'Wallis And Futuna Islands',
    iso3: 'WLF',
    iso2: 'WF',
    phoneCode: '681',
    capital: 'Mata Utu',
    currency: 'XPF',
    currencySymbol: r'₣',
    tld: '.wf',
    native: 'Wallis et Futuna',
    region: 'Oceania',
    subregion: 'Polynesia',
    timezones: [
      Timezone(
          zoneName: 'Pacific/Wallis',
          gmtOffset: 43200,
          gmtOffsetName: 'UTC+12:00',
          abbreviation: 'WFT',
          tzName: 'Wallis & Futuna Time')
    ],
    emoji: '🇼🇫',
    emojiU: 'U+1F1FC U+1F1EB',
    states: []);
