// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const omn = Country(
    id: 166,
    name: 'Oman',
    iso3: 'OMN',
    iso2: 'OM',
    phoneCode: '968',
    capital: 'Muscat',
    currency: 'OMR',
    currencySymbol: r'.ع.ر',
    tld: '.om',
    native: 'عمان',
    region: 'Asia',
    subregion: 'Western Asia',
    timezones: [
      Timezone(
          zoneName: 'Asia/Muscat',
          gmtOffset: 14400,
          gmtOffsetName: 'UTC+04:00',
          abbreviation: 'GST',
          tzName: 'Gulf Standard Time')
    ],
    emoji: '🇴🇲',
    emojiU: 'U+1F1F4 U+1F1F2',
    states: [
      State(
          id: 3058,
          name: 'Ad Dakhiliyah Governorate',
          stateCode: 'DA',
          cities: [
            City(
                id: 79926,
                name: 'Adam',
                latitude: '22.37934000',
                longitude: '57.52718000'),
            City(
                id: 79930,
                name: 'Bahlā’',
                latitude: '22.97886000',
                longitude: '57.30470000'),
            City(
                id: 79934,
                name: 'Bidbid',
                latitude: '23.40787000',
                longitude: '58.12830000'),
            City(
                id: 79937,
                name: 'Izkī',
                latitude: '22.93333000',
                longitude: '57.76667000'),
            City(
                id: 79942,
                name: 'Nizwá',
                latitude: '22.93333000',
                longitude: '57.53333000'),
            City(
                id: 79948,
                name: 'Sufālat Samā’il',
                latitude: '23.31667000',
                longitude: '58.01667000')
          ]),
      State(
          id: 3047,
          name: 'Ad Dhahirah Governorate',
          stateCode: 'ZA',
          cities: [
            City(
                id: 79953,
                name: '‘Ibrī',
                latitude: '23.22573000',
                longitude: '56.51572000'),
            City(
                id: 79950,
                name: 'Yanqul',
                latitude: '23.58645000',
                longitude: '56.53969000')
          ]),
      State(
          id: 3048,
          name: 'Al Batinah North Governorate',
          stateCode: 'BS',
          cities: [
            City(
                id: 79928,
                name: 'Al Khābūrah',
                latitude: '23.97144000',
                longitude: '57.09313000'),
            City(
                id: 79929,
                name: 'As Suwayq',
                latitude: '23.84944000',
                longitude: '57.43861000'),
            City(
                id: 79939,
                name: 'Liwá',
                latitude: '24.53077000',
                longitude: '56.56300000'),
            City(
                id: 79952,
                name: 'Şaḩam',
                latitude: '24.17222000',
                longitude: '56.88861000'),
            City(
                id: 79946,
                name: 'Shināş',
                latitude: '24.74260000',
                longitude: '56.46698000'),
            City(
                id: 79947,
                name: 'Sohar',
                latitude: '24.34745000',
                longitude: '56.70937000')
          ]),
      State(id: 3050, name: 'Al Batinah Region', stateCode: 'BA', cities: [
        City(
            id: 79931,
            name: 'Barkā’',
            latitude: '23.67872000',
            longitude: '57.88605000'),
        City(
            id: 79933,
            name: 'Bayt al ‘Awābī',
            latitude: '23.30324000',
            longitude: '57.52459000'),
        City(
            id: 79943,
            name: 'Oman Smart Future City',
            latitude: '23.65270000',
            longitude: '57.59926000'),
        City(
            id: 79944,
            name: 'Rustaq',
            latitude: '23.39083000',
            longitude: '57.42444000')
      ]),
      State(
          id: 3049,
          name: 'Al Batinah South Governorate',
          stateCode: 'BJ',
          cities: []),
      State(id: 3059, name: 'Al Buraimi Governorate', stateCode: 'BU', cities: [
        City(
            id: 79927,
            name: 'Al Buraymī',
            latitude: '24.25088000',
            longitude: '55.79312000')
      ]),
      State(id: 3056, name: 'Al Wusta Governorate', stateCode: 'WU', cities: [
        City(
            id: 79936,
            name: 'Haymā’',
            latitude: '19.95931000',
            longitude: '56.27575000')
      ]),
      State(
          id: 3053,
          name: 'Ash Sharqiyah North Governorate',
          stateCode: 'SS',
          cities: []),
      State(id: 3051, name: 'Ash Sharqiyah Region', stateCode: 'SH', cities: [
        City(
            id: 79949,
            name: 'Sur',
            latitude: '22.56667000',
            longitude: '59.52889000')
      ]),
      State(
          id: 3054,
          name: 'Ash Sharqiyah South Governorate',
          stateCode: 'SJ',
          cities: []),
      State(id: 3057, name: 'Dhofar Governorate', stateCode: 'ZU', cities: [
        City(
            id: 79951,
            name: 'Şalālah',
            latitude: '17.01505000',
            longitude: '54.09237000')
      ]),
      State(id: 3052, name: 'Musandam Governorate', stateCode: 'MU', cities: [
        City(
            id: 79935,
            name: 'Dib Dibba',
            latitude: '26.19778000',
            longitude: '56.25778000'),
        City(
            id: 79938,
            name: 'Khasab',
            latitude: '26.17993000',
            longitude: '56.24774000'),
        City(
            id: 79940,
            name: 'Madḩā’ al Jadīdah',
            latitude: '25.28345000',
            longitude: '56.33280000')
      ]),
      State(id: 3055, name: 'Muscat Governorate', stateCode: 'MA', cities: [
        City(
            id: 79932,
            name: 'Bawshar',
            latitude: '23.57769000',
            longitude: '58.39982000'),
        City(
            id: 79941,
            name: 'Muscat',
            latitude: '23.58413000',
            longitude: '58.40778000'),
        City(
            id: 79945,
            name: 'Seeb',
            latitude: '23.67027000',
            longitude: '58.18911000')
      ])
    ]);
