// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const syc = Country(
  id: 197,
  name: 'Seychelles',
  iso3: 'SYC',
  iso2: 'SC',
  phoneCode: '248',
  capital: 'Victoria',
  currency: 'SCR',
  currencySymbol: r'SRe',
  tld: '.sc',
  native: 'Seychelles',
  region: 'Africa',
  subregion: 'Eastern Africa',
  timezones: [
    Timezone(
      zoneName: 'Indian/Mahe',
      gmtOffset: 14400,
      gmtOffsetName: 'UTC+04:00',
      abbreviation: 'SCT',
      tzName: 'Seychelles Time',
    )
  ],
  emoji: '🇸🇨',
  emojiU: 'U+1F1F8 U+1F1E8',
  states: [
    CountryState(
      id: 513,
      name: 'Anse Boileau',
      stateCode: '02',
      cities: [
        City(
          id: 102906,
          name: 'Anse Boileau',
          latitude: '-4.71667000',
          longitude: '55.48333000',
        )
      ],
    ),
    CountryState(
      id: 502,
      name: 'Anse Royale',
      stateCode: '05',
      cities: [
        City(
          id: 102907,
          name: 'Anse Royale',
          latitude: '-4.73333000',
          longitude: '55.51667000',
        )
      ],
    ),
    CountryState(
      id: 506,
      name: 'Anse-aux-Pins',
      stateCode: '01',
      cities: [],
    ),
    CountryState(
      id: 508,
      name: 'Au Cap',
      stateCode: '04',
      cities: [],
    ),
    CountryState(
      id: 497,
      name: 'Baie Lazare',
      stateCode: '06',
      cities: [],
    ),
    CountryState(
      id: 514,
      name: 'Baie Sainte Anne',
      stateCode: '07',
      cities: [],
    ),
    CountryState(
      id: 512,
      name: 'Beau Vallon',
      stateCode: '08',
      cities: [
        City(
          id: 102908,
          name: 'Beau Vallon',
          latitude: '-4.62091000',
          longitude: '55.43015000',
        )
      ],
    ),
    CountryState(
      id: 515,
      name: 'Bel Air',
      stateCode: '09',
      cities: [],
    ),
    CountryState(
      id: 505,
      name: 'Bel Ombre',
      stateCode: '10',
      cities: [
        City(
          id: 102909,
          name: 'Bel Ombre',
          latitude: '-4.61667000',
          longitude: '55.41667000',
        )
      ],
    ),
    CountryState(
      id: 517,
      name: 'Cascade',
      stateCode: '11',
      cities: [
        City(
          id: 102910,
          name: 'Cascade',
          latitude: '-4.66667000',
          longitude: '55.50000000',
        )
      ],
    ),
    CountryState(
      id: 503,
      name: 'Glacis',
      stateCode: '12',
      cities: [],
    ),
    CountryState(
      id: 500,
      name: 'Grand\'Anse Mahé',
      stateCode: '13',
      cities: [],
    ),
    CountryState(
      id: 504,
      name: 'Grand\'Anse Praslin',
      stateCode: '14',
      cities: [],
    ),
    CountryState(
      id: 495,
      name: 'La Digue',
      stateCode: '15',
      cities: [],
    ),
    CountryState(
      id: 516,
      name: 'La Rivière Anglaise',
      stateCode: '16',
      cities: [
        City(
          id: 102913,
          name: 'Victoria',
          latitude: '-4.62001000',
          longitude: '55.45501000',
        )
      ],
    ),
    CountryState(
      id: 499,
      name: 'Les Mamelles',
      stateCode: '24',
      cities: [],
    ),
    CountryState(
      id: 494,
      name: 'Mont Buxton',
      stateCode: '17',
      cities: [],
    ),
    CountryState(
      id: 498,
      name: 'Mont Fleuri',
      stateCode: '18',
      cities: [],
    ),
    CountryState(
      id: 511,
      name: 'Plaisance',
      stateCode: '19',
      cities: [],
    ),
    CountryState(
      id: 510,
      name: 'Pointe La Rue',
      stateCode: '20',
      cities: [],
    ),
    CountryState(
      id: 507,
      name: 'Port Glaud',
      stateCode: '21',
      cities: [
        City(
          id: 102911,
          name: 'Port Glaud',
          latitude: '-4.66667000',
          longitude: '55.41667000',
        )
      ],
    ),
    CountryState(
      id: 501,
      name: 'Roche Caiman',
      stateCode: '25',
      cities: [],
    ),
    CountryState(
      id: 496,
      name: 'Saint Louis',
      stateCode: '22',
      cities: [],
    ),
    CountryState(
      id: 509,
      name: 'Takamaka',
      stateCode: '23',
      cities: [
        City(
          id: 102912,
          name: 'Takamaka',
          latitude: '-4.76667000',
          longitude: '55.50000000',
        )
      ],
    ),
  ],
);
