// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const mco = Country(
    id: 145,
    name: 'Monaco',
    iso3: 'MCO',
    iso2: 'MC',
    phoneCode: '377',
    capital: 'Monaco',
    currency: 'EUR',
    currencySymbol: r'€',
    tld: '.mc',
    native: 'Monaco',
    region: 'Europe',
    subregion: 'Western Europe',
    timezones: [
      Timezone(
          zoneName: 'Europe/Monaco',
          gmtOffset: 3600,
          gmtOffsetName: 'UTC+01:00',
          abbreviation: 'CET',
          tzName: 'Central European Time')
    ],
    emoji: '🇲🇨',
    emojiU: 'U+1F1F2 U+1F1E8',
    states: [
      State(id: 4917, name: 'La Colle', stateCode: 'CL', cities: []),
      State(id: 4918, name: 'La Condamine', stateCode: 'CO', cities: []),
      State(id: 4919, name: 'Moneghetti', stateCode: 'MG', cities: [])
    ]);
