// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const tls = Country(
  id: 63,
  name: 'East Timor',
  iso3: 'TLS',
  iso2: 'TL',
  phoneCode: '670',
  capital: 'Dili',
  currency: 'USD',
  currencySymbol: r'$',
  tld: '.tl',
  native: 'Timor-Leste',
  region: 'Asia',
  subregion: 'South-Eastern Asia',
  timezones: [
    Timezone(
      zoneName: 'Asia/Dili',
      gmtOffset: 32400,
      gmtOffsetName: 'UTC+09:00',
      abbreviation: 'TLT',
      tzName: 'Timor Leste Time',
    )
  ],
  emoji: '🇹🇱',
  emojiU: 'U+1F1F9 U+1F1F1',
  states: [
    CountryState(
      id: 4520,
      name: 'Aileu municipality',
      stateCode: 'AL',
      cities: [
        City(
          id: 106830,
          name: 'Aileu',
          latitude: '-8.72806000',
          longitude: '125.56639000',
        ),
        City(
          id: 106854,
          name: 'Lequidoe',
          latitude: '-8.69139000',
          longitude: '125.63611000',
        ),
        City(
          id: 106868,
          name: 'Remexio',
          latitude: '-8.61667000',
          longitude: '125.66667000',
        ),
      ],
    ),
    CountryState(
      id: 4518,
      name: 'Ainaro Municipality',
      stateCode: 'AN',
      cities: [
        City(
          id: 106831,
          name: 'Ainaro',
          latitude: '-8.99241000',
          longitude: '125.50816000',
        ),
        City(
          id: 106846,
          name: 'Hato-Udo',
          latitude: '-9.12036000',
          longitude: '125.58935000',
        ),
      ],
    ),
    CountryState(
      id: 4521,
      name: 'Baucau Municipality',
      stateCode: 'BA',
      cities: [
        City(
          id: 106834,
          name: 'Baguia',
          latitude: '-8.62787000',
          longitude: '126.65743000',
        ),
        City(
          id: 106836,
          name: 'Baucau',
          latitude: '-8.46667000',
          longitude: '126.45000000',
        ),
        City(
          id: 106837,
          name: 'Baukau',
          latitude: '-8.47572000',
          longitude: '126.45633000',
        ),
        City(
          id: 106852,
          name: 'Laga',
          latitude: '-8.47411000',
          longitude: '126.59228000',
        ),
        City(
          id: 106866,
          name: 'Quelicai',
          latitude: '-8.60135000',
          longitude: '126.55904000',
        ),
        City(
          id: 106877,
          name: 'Vemasse',
          latitude: '-8.51036000',
          longitude: '126.20823000',
        ),
        City(
          id: 106878,
          name: 'Venilale',
          latitude: '-8.64306000',
          longitude: '126.37833000',
        ),
      ],
    ),
    CountryState(
      id: 4525,
      name: 'Bobonaro Municipality',
      stateCode: 'BO',
      cities: [
        City(
          id: 106859,
          name: 'Maliana',
          latitude: '-8.99167000',
          longitude: '125.21972000',
        )
      ],
    ),
    CountryState(
      id: 4522,
      name: 'Cova Lima Municipality',
      stateCode: 'CO',
      cities: [
        City(
          id: 106843,
          name: 'Fatumean',
          latitude: '-9.22917000',
          longitude: '125.03583000',
        ),
        City(
          id: 106844,
          name: 'Fohorem',
          latitude: '-9.28361000',
          longitude: '125.08944000',
        ),
        City(
          id: 106863,
          name: 'Maucatar',
          latitude: '-9.21772000',
          longitude: '125.22981000',
        ),
        City(
          id: 106871,
          name: 'Suai',
          latitude: '-9.30000000',
          longitude: '125.25000000',
        ),
        City(
          id: 106872,
          name: 'Tilomar',
          latitude: '-9.34182000',
          longitude: '125.10887000',
        ),
      ],
    ),
    CountryState(
      id: 4524,
      name: 'Dili municipality',
      stateCode: 'DI',
      cities: [
        City(
          id: 106833,
          name: 'Atauro Island',
          latitude: '-8.26785000',
          longitude: '125.59699000',
        ),
        City(
          id: 106839,
          name: 'Cristo Rei',
          latitude: '-8.52047000',
          longitude: '125.60837000',
        ),
        City(
          id: 106840,
          name: 'Dili',
          latitude: '-8.55861000',
          longitude: '125.57361000',
        ),
        City(
          id: 106864,
          name: 'Metinaro',
          latitude: '-8.53007000',
          longitude: '125.74163000',
        ),
      ],
    ),
    CountryState(
      id: 4516,
      name: 'Ermera District',
      stateCode: 'ER',
      cities: [
        City(
          id: 106841,
          name: 'Ermera Villa',
          latitude: '-8.75222000',
          longitude: '125.39694000',
        ),
        City(
          id: 106845,
          name: 'Gleno',
          latitude: '-8.72389000',
          longitude: '125.43611000',
        ),
        City(
          id: 106847,
          name: 'Hatulia',
          latitude: '-8.81667000',
          longitude: '125.31667000',
        ),
        City(
          id: 106855,
          name: 'Letefoho',
          latitude: '-8.83444000',
          longitude: '125.42639000',
        ),
        City(
          id: 106867,
          name: 'Railaco',
          latitude: '-8.67237000',
          longitude: '125.42546000',
        ),
      ],
    ),
    CountryState(
      id: 4523,
      name: 'Lautém Municipality',
      stateCode: 'LA',
      cities: [
        City(
          id: 106848,
          name: 'Iliomar',
          latitude: '-8.70917000',
          longitude: '126.82833000',
        ),
        City(
          id: 106853,
          name: 'Lautem',
          latitude: '-8.36514000',
          longitude: '126.90389000',
        ),
        City(
          id: 106857,
          name: 'Lospalos',
          latitude: '-8.52167000',
          longitude: '126.99833000',
        ),
        City(
          id: 106858,
          name: 'Luro',
          latitude: '-8.54359000',
          longitude: '126.83003000',
        ),
        City(
          id: 106874,
          name: 'Tutuala',
          latitude: '-8.39597000',
          longitude: '127.25923000',
        ),
      ],
    ),
    CountryState(
      id: 4515,
      name: 'Liquiçá Municipality',
      stateCode: 'LI',
      cities: [
        City(
          id: 106838,
          name: 'Bazartete',
          latitude: '-8.62464000',
          longitude: '125.38168000',
        ),
        City(
          id: 106856,
          name: 'Likisá',
          latitude: '-8.58750000',
          longitude: '125.34194000',
        ),
        City(
          id: 106862,
          name: 'Maubara',
          latitude: '-8.61194000',
          longitude: '125.20611000',
        ),
      ],
    ),
    CountryState(
      id: 4517,
      name: 'Manatuto District',
      stateCode: 'MT',
      cities: [
        City(
          id: 106835,
          name: 'Barique',
          latitude: '-8.85472000',
          longitude: '126.06556000',
        ),
        City(
          id: 106849,
          name: 'Laclo',
          latitude: '-8.55000000',
          longitude: '125.91667000',
        ),
        City(
          id: 106850,
          name: 'Laclubar',
          latitude: '-8.74975000',
          longitude: '125.91186000',
        ),
        City(
          id: 106860,
          name: 'Manatuto',
          latitude: '-8.52207000',
          longitude: '126.01516000',
        ),
        City(
          id: 106861,
          name: 'Manatutu',
          latitude: '-8.51139000',
          longitude: '126.01306000',
        ),
        City(
          id: 106870,
          name: 'Soibada',
          latitude: '-8.86000000',
          longitude: '125.94000000',
        ),
      ],
    ),
    CountryState(
      id: 4519,
      name: 'Manufahi Municipality',
      stateCode: 'MF',
      cities: [
        City(
          id: 106832,
          name: 'Alas',
          latitude: '-9.02730000',
          longitude: '125.78680000',
        ),
        City(
          id: 106842,
          name: 'Fatuberliu',
          latitude: '-8.94790000',
          longitude: '125.86633000',
        ),
        City(
          id: 106869,
          name: 'Same',
          latitude: '-9.00000000',
          longitude: '125.65000000',
        ),
        City(
          id: 106873,
          name: 'Turiscai',
          latitude: '-8.82371000',
          longitude: '125.70454000',
        ),
      ],
    ),
    CountryState(
      id: 4514,
      name: 'Viqueque Municipality',
      stateCode: 'VI',
      cities: [
        City(
          id: 106851,
          name: 'Lacluta',
          latitude: '-8.80000000',
          longitude: '126.13333000',
        ),
        City(
          id: 106865,
          name: 'Ossu',
          latitude: '-8.73477000',
          longitude: '126.38324000',
        ),
        City(
          id: 106875,
          name: 'Uatocarabau',
          latitude: '-8.75658000',
          longitude: '126.68060000',
        ),
        City(
          id: 106876,
          name: 'Uatolari',
          latitude: '-8.76277000',
          longitude: '126.57353000',
        ),
        City(
          id: 106879,
          name: 'Viqueque',
          latitude: '-8.85908000',
          longitude: '126.36972000',
        ),
      ],
    ),
  ],
);
