// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const mtq = Country(
  id: 138,
  name: 'Martinique',
  iso3: 'MTQ',
  iso2: 'MQ',
  phoneCode: '596',
  capital: 'Fort-de-France',
  currency: 'EUR',
  currencySymbol: r'€',
  tld: '.mq',
  native: 'Martinique',
  region: 'Americas',
  subregion: 'Caribbean',
  timezones: [
    Timezone(
      zoneName: 'America/Martinique',
      gmtOffset: -14400,
      gmtOffsetName: 'UTC-04:00',
      abbreviation: 'AST',
      tzName: 'Atlantic Standard Time',
    )
  ],
  emoji: '🇲🇶',
  emojiU: 'U+1F1F2 U+1F1F6',
  states: [],
);
