// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const vut = Country(
    id: 237,
    name: 'Vanuatu',
    iso3: 'VUT',
    iso2: 'VU',
    phoneCode: '678',
    capital: 'Port Vila',
    currency: 'VUV',
    currencySymbol: r'VT',
    tld: '.vu',
    native: 'Vanuatu',
    region: 'Oceania',
    subregion: 'Melanesia',
    timezones: [
      Timezone(
          zoneName: 'Pacific/Efate',
          gmtOffset: 39600,
          gmtOffsetName: 'UTC+11:00',
          abbreviation: 'VUT',
          tzName: 'Vanuatu Time')
    ],
    emoji: '🇻🇺',
    emojiU: 'U+1F1FB U+1F1FA',
    states: [
      State(id: 4775, name: 'Malampa', stateCode: 'MAP', cities: [
        City(
            id: 130637,
            name: 'Lakatoro',
            latitude: '-16.09992000',
            longitude: '167.41636000'),
        City(
            id: 130639,
            name: 'Norsup',
            latitude: '-16.06536000',
            longitude: '167.39714000')
      ]),
      State(id: 4773, name: 'Penama', stateCode: 'PAM', cities: []),
      State(id: 4776, name: 'Sanma', stateCode: 'SAM', cities: [
        City(
            id: 130638,
            name: 'Luganville',
            latitude: '-15.51989000',
            longitude: '167.16235000'),
        City(
            id: 130640,
            name: 'Port-Olry',
            latitude: '-15.04175000',
            longitude: '167.07265000')
      ]),
      State(id: 4774, name: 'Shefa', stateCode: 'SEE', cities: [
        City(
            id: 130641,
            name: 'Port-Vila',
            latitude: '-17.73648000',
            longitude: '168.31366000')
      ]),
      State(id: 4777, name: 'Tafea', stateCode: 'TAE', cities: [
        City(
            id: 130636,
            name: 'Isangel',
            latitude: '-19.54167000',
            longitude: '169.28167000')
      ]),
      State(id: 4772, name: 'Torba', stateCode: 'TOB', cities: [
        City(
            id: 130642,
            name: 'Sola',
            latitude: '-13.87611000',
            longitude: '167.55167000')
      ])
    ]);
