// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/src/data/gen_afg.dart';
import 'package:country_state_city/src/data/gen_ala.dart';
import 'package:country_state_city/src/data/gen_alb.dart';
import 'package:country_state_city/src/data/gen_dza.dart';
import 'package:country_state_city/src/data/gen_asm.dart';
import 'package:country_state_city/src/data/gen_and.dart';
import 'package:country_state_city/src/data/gen_ago.dart';
import 'package:country_state_city/src/data/gen_aia.dart';
import 'package:country_state_city/src/data/gen_ata.dart';
import 'package:country_state_city/src/data/gen_atg.dart';
import 'package:country_state_city/src/data/gen_arg.dart';
import 'package:country_state_city/src/data/gen_arm.dart';
import 'package:country_state_city/src/data/gen_abw.dart';
import 'package:country_state_city/src/data/gen_aus.dart';
import 'package:country_state_city/src/data/gen_aut.dart';
import 'package:country_state_city/src/data/gen_aze.dart';
import 'package:country_state_city/src/data/gen_bhs.dart';
import 'package:country_state_city/src/data/gen_bhr.dart';
import 'package:country_state_city/src/data/gen_bgd.dart';
import 'package:country_state_city/src/data/gen_brb.dart';
import 'package:country_state_city/src/data/gen_blr.dart';
import 'package:country_state_city/src/data/gen_bel.dart';
import 'package:country_state_city/src/data/gen_blz.dart';
import 'package:country_state_city/src/data/gen_ben.dart';
import 'package:country_state_city/src/data/gen_bmu.dart';
import 'package:country_state_city/src/data/gen_btn.dart';
import 'package:country_state_city/src/data/gen_bol.dart';
import 'package:country_state_city/src/data/gen_bes.dart';
import 'package:country_state_city/src/data/gen_bih.dart';
import 'package:country_state_city/src/data/gen_bwa.dart';
import 'package:country_state_city/src/data/gen_bvt.dart';
import 'package:country_state_city/src/data/gen_bra.dart';
import 'package:country_state_city/src/data/gen_iot.dart';
import 'package:country_state_city/src/data/gen_brn.dart';
import 'package:country_state_city/src/data/gen_bgr.dart';
import 'package:country_state_city/src/data/gen_bfa.dart';
import 'package:country_state_city/src/data/gen_bdi.dart';
import 'package:country_state_city/src/data/gen_khm.dart';
import 'package:country_state_city/src/data/gen_cmr.dart';
import 'package:country_state_city/src/data/gen_can.dart';
import 'package:country_state_city/src/data/gen_cpv.dart';
import 'package:country_state_city/src/data/gen_cym.dart';
import 'package:country_state_city/src/data/gen_caf.dart';
import 'package:country_state_city/src/data/gen_tcd.dart';
import 'package:country_state_city/src/data/gen_chl.dart';
import 'package:country_state_city/src/data/gen_chn.dart';
import 'package:country_state_city/src/data/gen_cxr.dart';
import 'package:country_state_city/src/data/gen_cck.dart';
import 'package:country_state_city/src/data/gen_col.dart';
import 'package:country_state_city/src/data/gen_com.dart';
import 'package:country_state_city/src/data/gen_cog.dart';
import 'package:country_state_city/src/data/gen_cod.dart';
import 'package:country_state_city/src/data/gen_cok.dart';
import 'package:country_state_city/src/data/gen_cri.dart';
import 'package:country_state_city/src/data/gen_civ.dart';
import 'package:country_state_city/src/data/gen_hrv.dart';
import 'package:country_state_city/src/data/gen_cub.dart';
import 'package:country_state_city/src/data/gen_cuw.dart';
import 'package:country_state_city/src/data/gen_cyp.dart';
import 'package:country_state_city/src/data/gen_cze.dart';
import 'package:country_state_city/src/data/gen_dnk.dart';
import 'package:country_state_city/src/data/gen_dji.dart';
import 'package:country_state_city/src/data/gen_dma.dart';
import 'package:country_state_city/src/data/gen_dom.dart';
import 'package:country_state_city/src/data/gen_tls.dart';
import 'package:country_state_city/src/data/gen_ecu.dart';
import 'package:country_state_city/src/data/gen_egy.dart';
import 'package:country_state_city/src/data/gen_slv.dart';
import 'package:country_state_city/src/data/gen_gnq.dart';
import 'package:country_state_city/src/data/gen_eri.dart';
import 'package:country_state_city/src/data/gen_est.dart';
import 'package:country_state_city/src/data/gen_eth.dart';
import 'package:country_state_city/src/data/gen_flk.dart';
import 'package:country_state_city/src/data/gen_fro.dart';
import 'package:country_state_city/src/data/gen_fji.dart';
import 'package:country_state_city/src/data/gen_fin.dart';
import 'package:country_state_city/src/data/gen_fra.dart';
import 'package:country_state_city/src/data/gen_guf.dart';
import 'package:country_state_city/src/data/gen_pyf.dart';
import 'package:country_state_city/src/data/gen_atf.dart';
import 'package:country_state_city/src/data/gen_gab.dart';
import 'package:country_state_city/src/data/gen_gmb.dart';
import 'package:country_state_city/src/data/gen_geo.dart';
import 'package:country_state_city/src/data/gen_deu.dart';
import 'package:country_state_city/src/data/gen_gha.dart';
import 'package:country_state_city/src/data/gen_gib.dart';
import 'package:country_state_city/src/data/gen_grc.dart';
import 'package:country_state_city/src/data/gen_grl.dart';
import 'package:country_state_city/src/data/gen_grd.dart';
import 'package:country_state_city/src/data/gen_glp.dart';
import 'package:country_state_city/src/data/gen_gum.dart';
import 'package:country_state_city/src/data/gen_gtm.dart';
import 'package:country_state_city/src/data/gen_ggy.dart';
import 'package:country_state_city/src/data/gen_gin.dart';
import 'package:country_state_city/src/data/gen_gnb.dart';
import 'package:country_state_city/src/data/gen_guy.dart';
import 'package:country_state_city/src/data/gen_hti.dart';
import 'package:country_state_city/src/data/gen_hmd.dart';
import 'package:country_state_city/src/data/gen_hnd.dart';
import 'package:country_state_city/src/data/gen_hkg.dart';
import 'package:country_state_city/src/data/gen_hun.dart';
import 'package:country_state_city/src/data/gen_isl.dart';
import 'package:country_state_city/src/data/gen_ind.dart';
import 'package:country_state_city/src/data/gen_idn.dart';
import 'package:country_state_city/src/data/gen_irn.dart';
import 'package:country_state_city/src/data/gen_irq.dart';
import 'package:country_state_city/src/data/gen_irl.dart';
import 'package:country_state_city/src/data/gen_isr.dart';
import 'package:country_state_city/src/data/gen_ita.dart';
import 'package:country_state_city/src/data/gen_jam.dart';
import 'package:country_state_city/src/data/gen_jpn.dart';
import 'package:country_state_city/src/data/gen_jey.dart';
import 'package:country_state_city/src/data/gen_jor.dart';
import 'package:country_state_city/src/data/gen_kaz.dart';
import 'package:country_state_city/src/data/gen_ken.dart';
import 'package:country_state_city/src/data/gen_kir.dart';
import 'package:country_state_city/src/data/gen_prk.dart';
import 'package:country_state_city/src/data/gen_kor.dart';
import 'package:country_state_city/src/data/gen_xkx.dart';
import 'package:country_state_city/src/data/gen_kwt.dart';
import 'package:country_state_city/src/data/gen_kgz.dart';
import 'package:country_state_city/src/data/gen_lao.dart';
import 'package:country_state_city/src/data/gen_lva.dart';
import 'package:country_state_city/src/data/gen_lbn.dart';
import 'package:country_state_city/src/data/gen_lso.dart';
import 'package:country_state_city/src/data/gen_lbr.dart';
import 'package:country_state_city/src/data/gen_lby.dart';
import 'package:country_state_city/src/data/gen_lie.dart';
import 'package:country_state_city/src/data/gen_ltu.dart';
import 'package:country_state_city/src/data/gen_lux.dart';
import 'package:country_state_city/src/data/gen_mac.dart';
import 'package:country_state_city/src/data/gen_mkd.dart';
import 'package:country_state_city/src/data/gen_mdg.dart';
import 'package:country_state_city/src/data/gen_mwi.dart';
import 'package:country_state_city/src/data/gen_mys.dart';
import 'package:country_state_city/src/data/gen_mdv.dart';
import 'package:country_state_city/src/data/gen_mli.dart';
import 'package:country_state_city/src/data/gen_mlt.dart';
import 'package:country_state_city/src/data/gen_imn.dart';
import 'package:country_state_city/src/data/gen_mhl.dart';
import 'package:country_state_city/src/data/gen_mtq.dart';
import 'package:country_state_city/src/data/gen_mrt.dart';
import 'package:country_state_city/src/data/gen_mus.dart';
import 'package:country_state_city/src/data/gen_myt.dart';
import 'package:country_state_city/src/data/gen_mex.dart';
import 'package:country_state_city/src/data/gen_fsm.dart';
import 'package:country_state_city/src/data/gen_mda.dart';
import 'package:country_state_city/src/data/gen_mco.dart';
import 'package:country_state_city/src/data/gen_mng.dart';
import 'package:country_state_city/src/data/gen_mne.dart';
import 'package:country_state_city/src/data/gen_msr.dart';
import 'package:country_state_city/src/data/gen_mar.dart';
import 'package:country_state_city/src/data/gen_moz.dart';
import 'package:country_state_city/src/data/gen_mmr.dart';
import 'package:country_state_city/src/data/gen_nam.dart';
import 'package:country_state_city/src/data/gen_nru.dart';
import 'package:country_state_city/src/data/gen_npl.dart';
import 'package:country_state_city/src/data/gen_nld.dart';
import 'package:country_state_city/src/data/gen_ncl.dart';
import 'package:country_state_city/src/data/gen_nzl.dart';
import 'package:country_state_city/src/data/gen_nic.dart';
import 'package:country_state_city/src/data/gen_ner.dart';
import 'package:country_state_city/src/data/gen_nga.dart';
import 'package:country_state_city/src/data/gen_niu.dart';
import 'package:country_state_city/src/data/gen_nfk.dart';
import 'package:country_state_city/src/data/gen_mnp.dart';
import 'package:country_state_city/src/data/gen_nor.dart';
import 'package:country_state_city/src/data/gen_omn.dart';
import 'package:country_state_city/src/data/gen_pak.dart';
import 'package:country_state_city/src/data/gen_plw.dart';
import 'package:country_state_city/src/data/gen_pse.dart';
import 'package:country_state_city/src/data/gen_pan.dart';
import 'package:country_state_city/src/data/gen_png.dart';
import 'package:country_state_city/src/data/gen_pry.dart';
import 'package:country_state_city/src/data/gen_per.dart';
import 'package:country_state_city/src/data/gen_phl.dart';
import 'package:country_state_city/src/data/gen_pcn.dart';
import 'package:country_state_city/src/data/gen_pol.dart';
import 'package:country_state_city/src/data/gen_prt.dart';
import 'package:country_state_city/src/data/gen_pri.dart';
import 'package:country_state_city/src/data/gen_qat.dart';
import 'package:country_state_city/src/data/gen_reu.dart';
import 'package:country_state_city/src/data/gen_rou.dart';
import 'package:country_state_city/src/data/gen_rus.dart';
import 'package:country_state_city/src/data/gen_rwa.dart';
import 'package:country_state_city/src/data/gen_shn.dart';
import 'package:country_state_city/src/data/gen_kna.dart';
import 'package:country_state_city/src/data/gen_lca.dart';
import 'package:country_state_city/src/data/gen_spm.dart';
import 'package:country_state_city/src/data/gen_vct.dart';
import 'package:country_state_city/src/data/gen_blm.dart';
import 'package:country_state_city/src/data/gen_maf.dart';
import 'package:country_state_city/src/data/gen_wsm.dart';
import 'package:country_state_city/src/data/gen_smr.dart';
import 'package:country_state_city/src/data/gen_stp.dart';
import 'package:country_state_city/src/data/gen_sau.dart';
import 'package:country_state_city/src/data/gen_sen.dart';
import 'package:country_state_city/src/data/gen_srb.dart';
import 'package:country_state_city/src/data/gen_syc.dart';
import 'package:country_state_city/src/data/gen_sle.dart';
import 'package:country_state_city/src/data/gen_sgp.dart';
import 'package:country_state_city/src/data/gen_sxm.dart';
import 'package:country_state_city/src/data/gen_svk.dart';
import 'package:country_state_city/src/data/gen_svn.dart';
import 'package:country_state_city/src/data/gen_slb.dart';
import 'package:country_state_city/src/data/gen_som.dart';
import 'package:country_state_city/src/data/gen_zaf.dart';
import 'package:country_state_city/src/data/gen_sgs.dart';
import 'package:country_state_city/src/data/gen_ssd.dart';
import 'package:country_state_city/src/data/gen_esp.dart';
import 'package:country_state_city/src/data/gen_lka.dart';
import 'package:country_state_city/src/data/gen_sdn.dart';
import 'package:country_state_city/src/data/gen_sur.dart';
import 'package:country_state_city/src/data/gen_sjm.dart';
import 'package:country_state_city/src/data/gen_swz.dart';
import 'package:country_state_city/src/data/gen_swe.dart';
import 'package:country_state_city/src/data/gen_che.dart';
import 'package:country_state_city/src/data/gen_syr.dart';
import 'package:country_state_city/src/data/gen_twn.dart';
import 'package:country_state_city/src/data/gen_tjk.dart';
import 'package:country_state_city/src/data/gen_tza.dart';
import 'package:country_state_city/src/data/gen_tha.dart';
import 'package:country_state_city/src/data/gen_tgo.dart';
import 'package:country_state_city/src/data/gen_tkl.dart';
import 'package:country_state_city/src/data/gen_ton.dart';
import 'package:country_state_city/src/data/gen_tto.dart';
import 'package:country_state_city/src/data/gen_tun.dart';
import 'package:country_state_city/src/data/gen_tur.dart';
import 'package:country_state_city/src/data/gen_tkm.dart';
import 'package:country_state_city/src/data/gen_tca.dart';
import 'package:country_state_city/src/data/gen_tuv.dart';
import 'package:country_state_city/src/data/gen_uga.dart';
import 'package:country_state_city/src/data/gen_ukr.dart';
import 'package:country_state_city/src/data/gen_are.dart';
import 'package:country_state_city/src/data/gen_gbr.dart';
import 'package:country_state_city/src/data/gen_usa.dart';
import 'package:country_state_city/src/data/gen_umi.dart';
import 'package:country_state_city/src/data/gen_ury.dart';
import 'package:country_state_city/src/data/gen_uzb.dart';
import 'package:country_state_city/src/data/gen_vut.dart';
import 'package:country_state_city/src/data/gen_vat.dart';
import 'package:country_state_city/src/data/gen_ven.dart';
import 'package:country_state_city/src/data/gen_vnm.dart';
import 'package:country_state_city/src/data/gen_vgb.dart';
import 'package:country_state_city/src/data/gen_vir.dart';
import 'package:country_state_city/src/data/gen_wlf.dart';
import 'package:country_state_city/src/data/gen_esh.dart';
import 'package:country_state_city/src/data/gen_yem.dart';
import 'package:country_state_city/src/data/gen_zmb.dart';
import 'package:country_state_city/src/data/gen_zwe.dart';

const kCountries = [
  afg,
  ala,
  alb,
  dza,
  asm,
  and,
  ago,
  aia,
  ata,
  atg,
  arg,
  arm,
  abw,
  aus,
  aut,
  aze,
  bhs,
  bhr,
  bgd,
  brb,
  blr,
  bel,
  blz,
  ben,
  bmu,
  btn,
  bol,
  bes,
  bih,
  bwa,
  bvt,
  bra,
  iot,
  brn,
  bgr,
  bfa,
  bdi,
  khm,
  cmr,
  can,
  cpv,
  cym,
  caf,
  tcd,
  chl,
  chn,
  cxr,
  cck,
  col,
  com,
  cog,
  cod,
  cok,
  cri,
  civ,
  hrv,
  cub,
  cuw,
  cyp,
  cze,
  dnk,
  dji,
  dma,
  dom,
  tls,
  ecu,
  egy,
  slv,
  gnq,
  eri,
  est,
  eth,
  flk,
  fro,
  fji,
  fin,
  fra,
  guf,
  pyf,
  atf,
  gab,
  gmb,
  geo,
  deu,
  gha,
  gib,
  grc,
  grl,
  grd,
  glp,
  gum,
  gtm,
  ggy,
  gin,
  gnb,
  guy,
  hti,
  hmd,
  hnd,
  hkg,
  hun,
  isl,
  ind,
  idn,
  irn,
  irq,
  irl,
  isr,
  ita,
  jam,
  jpn,
  jey,
  jor,
  kaz,
  ken,
  kir,
  prk,
  kor,
  xkx,
  kwt,
  kgz,
  lao,
  lva,
  lbn,
  lso,
  lbr,
  lby,
  lie,
  ltu,
  lux,
  mac,
  mkd,
  mdg,
  mwi,
  mys,
  mdv,
  mli,
  mlt,
  imn,
  mhl,
  mtq,
  mrt,
  mus,
  myt,
  mex,
  fsm,
  mda,
  mco,
  mng,
  mne,
  msr,
  mar,
  moz,
  mmr,
  nam,
  nru,
  npl,
  nld,
  ncl,
  nzl,
  nic,
  ner,
  nga,
  niu,
  nfk,
  mnp,
  nor,
  omn,
  pak,
  plw,
  pse,
  pan,
  png,
  pry,
  per,
  phl,
  pcn,
  pol,
  prt,
  pri,
  qat,
  reu,
  rou,
  rus,
  rwa,
  shn,
  kna,
  lca,
  spm,
  vct,
  blm,
  maf,
  wsm,
  smr,
  stp,
  sau,
  sen,
  srb,
  syc,
  sle,
  sgp,
  sxm,
  svk,
  svn,
  slb,
  som,
  zaf,
  sgs,
  ssd,
  esp,
  lka,
  sdn,
  sur,
  sjm,
  swz,
  swe,
  che,
  syr,
  twn,
  tjk,
  tza,
  tha,
  tgo,
  tkl,
  ton,
  tto,
  tun,
  tur,
  tkm,
  tca,
  tuv,
  uga,
  ukr,
  are,
  gbr,
  usa,
  umi,
  ury,
  uzb,
  vut,
  vat,
  ven,
  vnm,
  vgb,
  vir,
  wlf,
  esh,
  yem,
  zmb,
  zwe
];
