// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const tto = Country(
  id: 223,
  name: 'Trinidad And Tobago',
  iso3: 'TTO',
  iso2: 'TT',
  phoneCode: '+1-868',
  capital: 'Port of Spain',
  currency: 'TTD',
  currencySymbol: r'$',
  tld: '.tt',
  native: 'Trinidad and Tobago',
  region: 'Americas',
  subregion: 'Caribbean',
  timezones: [
    Timezone(
      zoneName: 'America/Port_of_Spain',
      gmtOffset: -14400,
      gmtOffsetName: 'UTC-04:00',
      abbreviation: 'AST',
      tzName: 'Atlantic Standard Time',
    )
  ],
  emoji: '🇹🇹',
  emojiU: 'U+1F1F9 U+1F1F9',
  states: [
    CountryState(
      id: 3362,
      name: 'Arima',
      stateCode: 'ARI',
      cities: [
        City(
          id: 108968,
          name: 'Arima',
          latitude: '10.63737000',
          longitude: '-61.28228000',
        )
      ],
    ),
    CountryState(
      id: 3366,
      name: 'Chaguanas',
      stateCode: 'CHA',
      cities: [
        City(
          id: 108970,
          name: 'Chaguanas',
          latitude: '10.51667000',
          longitude: '-61.41667000',
        ),
        City(
          id: 108990,
          name: 'Ward of Chaguanas',
          latitude: '10.50000000',
          longitude: '-61.38333000',
        ),
      ],
    ),
    CountryState(
      id: 3354,
      name: 'Couva-Tabaquite-Talparo Regional Corporation',
      stateCode: 'CTT',
      cities: [
        City(
          id: 108971,
          name: 'Couva',
          latitude: '10.42248000',
          longitude: '-61.46748000',
        ),
        City(
          id: 108988,
          name: 'Tabaquite',
          latitude: '10.38824000',
          longitude: '-61.29704000',
        ),
      ],
    ),
    CountryState(
      id: 3367,
      name: 'Diego Martin Regional Corporation',
      stateCode: 'DMN',
      cities: [
        City(
          id: 108978,
          name: 'Petit Valley',
          latitude: '10.69974000',
          longitude: '-61.54717000',
        ),
        City(
          id: 108991,
          name: 'Ward of Diego Martin',
          latitude: '10.70000000',
          longitude: '-61.58333000',
        ),
      ],
    ),
    CountryState(
      id: 3355,
      name: 'Eastern Tobago',
      stateCode: 'ETO',
      cities: [
        City(
          id: 108986,
          name: 'Scarborough',
          latitude: '11.18229000',
          longitude: '-60.73525000',
        )
      ],
    ),
    CountryState(
      id: 3365,
      name: 'Penal-Debe Regional Corporation',
      stateCode: 'PED',
      cities: [
        City(
          id: 108972,
          name: 'Debe',
          latitude: '10.20846000',
          longitude: '-61.45273000',
        ),
        City(
          id: 108979,
          name: 'Peñal',
          latitude: '10.16667000',
          longitude: '-61.46667000',
        ),
      ],
    ),
    CountryState(
      id: 3360,
      name: 'Point Fortin',
      stateCode: 'PTF',
      cities: [
        City(
          id: 108980,
          name: 'Point Fortin',
          latitude: '10.17411000',
          longitude: '-61.68407000',
        )
      ],
    ),
    CountryState(
      id: 3363,
      name: 'Port of Spain',
      stateCode: 'POS',
      cities: [
        City(
          id: 108976,
          name: 'Mucurapo',
          latitude: '10.66253000',
          longitude: '-61.53697000',
        ),
        City(
          id: 108981,
          name: 'Port of Spain',
          latitude: '10.66668000',
          longitude: '-61.51889000',
        ),
      ],
    ),
    CountryState(
      id: 3368,
      name: 'Princes Town Regional Corporation',
      stateCode: 'PRT',
      cities: [
        City(
          id: 108982,
          name: 'Princes Town',
          latitude: '10.27184000',
          longitude: '-61.37103000',
        )
      ],
    ),
    CountryState(
      id: 3356,
      name: 'Rio Claro-Mayaro Regional Corporation',
      stateCode: 'MRC',
      cities: [],
    ),
    CountryState(
      id: 3359,
      name: 'San Fernando',
      stateCode: 'SFO',
      cities: [
        City(
          id: 108974,
          name: 'Marabella',
          latitude: '10.30618000',
          longitude: '-61.44671000',
        ),
        City(
          id: 108975,
          name: 'Mon Repos',
          latitude: '10.27979000',
          longitude: '-61.44590000',
        ),
        City(
          id: 108984,
          name: 'San Fernando',
          latitude: '10.27969000',
          longitude: '-61.46835000',
        ),
      ],
    ),
    CountryState(
      id: 3357,
      name: 'San Juan-Laventille Regional Corporation',
      stateCode: 'SJL',
      cities: [
        City(
          id: 108973,
          name: 'Laventille',
          latitude: '10.64917000',
          longitude: '-61.49889000',
        )
      ],
    ),
    CountryState(
      id: 3361,
      name: 'Sangre Grande Regional Corporation',
      stateCode: 'SGE',
      cities: [
        City(
          id: 108985,
          name: 'Sangre Grande',
          latitude: '10.58705000',
          longitude: '-61.13008000',
        )
      ],
    ),
    CountryState(
      id: 3364,
      name: 'Siparia Regional Corporation',
      stateCode: 'SIP',
      cities: [
        City(
          id: 108987,
          name: 'Siparia',
          latitude: '10.14525000',
          longitude: '-61.50740000',
        ),
        City(
          id: 108992,
          name: 'Ward of Siparia',
          latitude: '10.15000000',
          longitude: '-61.46667000',
        ),
      ],
    ),
    CountryState(
      id: 3358,
      name: 'Tunapuna-Piarco Regional Corporation',
      stateCode: 'TUP',
      cities: [
        City(
          id: 108969,
          name: 'Arouca',
          latitude: '10.62877000',
          longitude: '-61.33487000',
        ),
        City(
          id: 108977,
          name: 'Paradise',
          latitude: '10.65298000',
          longitude: '-61.36298000',
        ),
        City(
          id: 108989,
          name: 'Tunapuna',
          latitude: '10.65245000',
          longitude: '-61.38878000',
        ),
      ],
    ),
    CountryState(
      id: 3353,
      name: 'Western Tobago',
      stateCode: 'WTO',
      cities: [
        City(
          id: 108983,
          name: 'Rio Claro',
          latitude: '10.30594000',
          longitude: '-61.17556000',
        )
      ],
    ),
  ],
);
