// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const ala = Country(
    id: 2,
    name: 'Aland Islands',
    iso3: 'ALA',
    iso2: 'AX',
    phoneCode: '+358-18',
    capital: 'Mariehamn',
    currency: 'EUR',
    currencySymbol: r'€',
    tld: '.ax',
    native: 'Åland',
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: [
      Timezone(
          zoneName: 'Europe/Mariehamn',
          gmtOffset: 7200,
          gmtOffsetName: 'UTC+02:00',
          abbreviation: 'EET',
          tzName: 'Eastern European Time')
    ],
    emoji: '🇦🇽',
    emojiU: 'U+1F1E6 U+1F1FD',
    states: []);
