// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const lie = Country(
  id: 125,
  name: 'Liechtenstein',
  iso3: 'LIE',
  iso2: 'LI',
  phoneCode: '423',
  capital: 'Vaduz',
  currency: 'CHF',
  currencySymbol: r'CHf',
  tld: '.li',
  native: 'Liechtenstein',
  region: 'Europe',
  subregion: 'Western Europe',
  timezones: [
    Timezone(
      zoneName: 'Europe/Vaduz',
      gmtOffset: 3600,
      gmtOffsetName: 'UTC+01:00',
      abbreviation: 'CET',
      tzName: 'Central European Time',
    )
  ],
  emoji: '🇱🇮',
  emojiU: 'U+1F1F1 U+1F1EE',
  states: [
    CountryState(
      id: 458,
      name: 'Balzers',
      stateCode: '01',
      cities: [
        City(
          id: 66437,
          name: 'Balzers',
          latitude: '47.06665000',
          longitude: '9.50251000',
        )
      ],
    ),
    CountryState(
      id: 451,
      name: 'Eschen',
      stateCode: '02',
      cities: [
        City(
          id: 66438,
          name: 'Eschen',
          latitude: '47.21071000',
          longitude: '9.52223000',
        )
      ],
    ),
    CountryState(
      id: 457,
      name: 'Gamprin',
      stateCode: '03',
      cities: [
        City(
          id: 66439,
          name: 'Gamprin',
          latitude: '47.22038000',
          longitude: '9.50935000',
        )
      ],
    ),
    CountryState(
      id: 455,
      name: 'Mauren',
      stateCode: '04',
      cities: [
        City(
          id: 66440,
          name: 'Mauren',
          latitude: '47.21805000',
          longitude: '9.54420000',
        )
      ],
    ),
    CountryState(
      id: 454,
      name: 'Planken',
      stateCode: '05',
      cities: [
        City(
          id: 66441,
          name: 'Planken',
          latitude: '47.18516000',
          longitude: '9.54437000',
        )
      ],
    ),
    CountryState(
      id: 453,
      name: 'Ruggell',
      stateCode: '06',
      cities: [
        City(
          id: 66442,
          name: 'Ruggell',
          latitude: '47.23799000',
          longitude: '9.52540000',
        )
      ],
    ),
    CountryState(
      id: 450,
      name: 'Schaan',
      stateCode: '07',
      cities: [
        City(
          id: 66443,
          name: 'Schaan',
          latitude: '47.16498000',
          longitude: '9.50867000',
        )
      ],
    ),
    CountryState(
      id: 449,
      name: 'Schellenberg',
      stateCode: '08',
      cities: [
        City(
          id: 66444,
          name: 'Schellenberg',
          latitude: '47.23123000',
          longitude: '9.54678000',
        )
      ],
    ),
    CountryState(
      id: 459,
      name: 'Triesen',
      stateCode: '09',
      cities: [
        City(
          id: 66445,
          name: 'Triesen',
          latitude: '47.10752000',
          longitude: '9.52815000',
        )
      ],
    ),
    CountryState(
      id: 456,
      name: 'Triesenberg',
      stateCode: '10',
      cities: [
        City(
          id: 66446,
          name: 'Triesenberg',
          latitude: '47.11815000',
          longitude: '9.54197000',
        )
      ],
    ),
    CountryState(
      id: 452,
      name: 'Vaduz',
      stateCode: '11',
      cities: [
        City(
          id: 66447,
          name: 'Vaduz',
          latitude: '47.14151000',
          longitude: '9.52154000',
        )
      ],
    ),
  ],
);
