// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const ggy = Country(
    id: 91,
    name: 'Guernsey and Alderney',
    iso3: 'GGY',
    iso2: 'GG',
    phoneCode: '+44-1481',
    capital: 'St Peter Port',
    currency: 'GBP',
    currencySymbol: r'£',
    tld: '.gg',
    native: 'Guernsey',
    region: 'Europe',
    subregion: 'Northern Europe',
    timezones: [
      Timezone(
          zoneName: 'Europe/Guernsey',
          gmtOffset: 0,
          gmtOffsetName: 'UTC±00',
          abbreviation: 'GMT',
          tzName: 'Greenwich Mean Time')
    ],
    emoji: '🇬🇬',
    emojiU: 'U+1F1EC U+1F1EC',
    states: []);
