// This file is automatically generated. DO NOT EDIT manually.

import 'package:country_state_city/country_state_city.dart';

const chl = Country(
    id: 44,
    name: 'Chile',
    iso3: 'CHL',
    iso2: 'CL',
    phoneCode: '56',
    capital: 'Santiago',
    currency: 'CLP',
    currencySymbol: r'$',
    tld: '.cl',
    native: 'Chile',
    region: 'Americas',
    subregion: 'South America',
    timezones: [
      Timezone(
          zoneName: 'America/Punta_Arenas',
          gmtOffset: -10800,
          gmtOffsetName: 'UTC-03:00',
          abbreviation: 'CLST',
          tzName: 'Chile Summer Time'),
      Timezone(
          zoneName: 'America/Santiago',
          gmtOffset: -10800,
          gmtOffsetName: 'UTC-03:00',
          abbreviation: 'CLST',
          tzName: 'Chile Summer Time'),
      Timezone(
          zoneName: 'Pacific/Easter',
          gmtOffset: -18000,
          gmtOffsetName: 'UTC-05:00',
          abbreviation: 'EASST',
          tzName: 'Easter Island Summer Time')
    ],
    emoji: '🇨🇱',
    emojiU: 'U+1F1E8 U+1F1F1',
    states: [
      State(id: 2832, name: 'Antofagasta Region', stateCode: 'AN', cities: [
        City(
            id: 18946,
            name: 'Antofagasta',
            latitude: '-23.65236000',
            longitude: '-70.39540000'),
        City(
            id: 18952,
            name: 'Calama',
            latitude: '-22.45667000',
            longitude: '-68.92371000'),
        City(
            id: 19033,
            name: 'Provincia de Antofagasta',
            latitude: '-24.31122000',
            longitude: '-69.57084000'),
        City(
            id: 19051,
            name: 'Provincia de El Loa',
            latitude: '-22.96764000',
            longitude: '-68.18716000'),
        City(
            id: 19074,
            name: 'Provincia de Tocopilla',
            latitude: '-22.02949000',
            longitude: '-69.64006000'),
        City(
            id: 19107,
            name: 'San Pedro de Atacama',
            latitude: '-22.91110000',
            longitude: '-68.20113000'),
        City(
            id: 19115,
            name: 'Taltal',
            latitude: '-25.40713000',
            longitude: '-70.48554000'),
        City(
            id: 19118,
            name: 'Tocopilla',
            latitude: '-22.09198000',
            longitude: '-70.19792000')
      ]),
      State(id: 2826, name: 'Araucanía Region', stateCode: 'AR', cities: [
        City(
            id: 18945,
            name: 'Angol',
            latitude: '-37.79519000',
            longitude: '-72.71636000'),
        City(
            id: 18954,
            name: 'Carahue',
            latitude: '-38.71122000',
            longitude: '-73.16101000'),
        City(
            id: 18969,
            name: 'Collipulli',
            latitude: '-37.95453000',
            longitude: '-72.43438000'),
        City(
            id: 18983,
            name: 'Freire',
            latitude: '-38.95252000',
            longitude: '-72.62653000'),
        City(
            id: 19000,
            name: 'Lautaro',
            latitude: '-38.53066000',
            longitude: '-72.43652000'),
        City(
            id: 19006,
            name: 'Loncoche',
            latitude: '-39.36708000',
            longitude: '-72.63087000'),
        City(
            id: 19017,
            name: 'Nueva Imperial',
            latitude: '-38.74451000',
            longitude: '-72.95025000'),
        City(
            id: 19027,
            name: 'Pitrufquén',
            latitude: '-38.98635000',
            longitude: '-72.63721000'),
        City(
            id: 19040,
            name: 'Provincia de Cautín',
            latitude: '-38.94719000',
            longitude: '-72.36198000'),
        City(
            id: 19062,
            name: 'Provincia de Malleco',
            latitude: '-38.23591000',
            longitude: '-72.13034000'),
        City(
            id: 19080,
            name: 'Pucón',
            latitude: '-39.28223000',
            longitude: '-71.95427000'),
        City(
            id: 19116,
            name: 'Temuco',
            latitude: '-38.73965000',
            longitude: '-72.59842000'),
        City(
            id: 19120,
            name: 'Traiguén',
            latitude: '-38.24960000',
            longitude: '-72.67027000'),
        City(
            id: 19124,
            name: 'Victoria',
            latitude: '-38.23291000',
            longitude: '-72.33292000'),
        City(
            id: 19126,
            name: 'Vilcún',
            latitude: '-38.66875000',
            longitude: '-72.22565000'),
        City(
            id: 19129,
            name: 'Villarrica',
            latitude: '-39.28569000',
            longitude: '-72.22790000')
      ]),
      State(
          id: 2829,
          name: 'Arica y Parinacota Region',
          stateCode: 'AP',
          cities: [
            City(
                id: 18948,
                name: 'Arica',
                latitude: '-18.47460000',
                longitude: '-70.29792000'),
            City(
                id: 19035,
                name: 'Provincia de Arica',
                latitude: '-18.70643000',
                longitude: '-69.85607000'),
            City(
                id: 19067,
                name: 'Provincia de Parinacota',
                latitude: '-18.19804000',
                longitude: '-69.57161000')
          ]),
      State(id: 2823, name: 'Atacama Region', stateCode: 'AT', cities: [
        City(
            id: 18972,
            name: 'Copiapó',
            latitude: '-27.36679000',
            longitude: '-70.33140000'),
        City(
            id: 18981,
            name: 'Diego de Almagro',
            latitude: '-26.36667000',
            longitude: '-70.05000000'),
        City(
            id: 19042,
            name: 'Provincia de Chañaral',
            latitude: '-26.32515000',
            longitude: '-69.48751000'),
        City(
            id: 19047,
            name: 'Provincia de Copiapó',
            latitude: '-27.56347000',
            longitude: '-70.00063000'),
        City(
            id: 19053,
            name: 'Provincia de Huasco',
            latitude: '-28.68428000',
            longitude: '-70.51474000'),
        City(
            id: 19122,
            name: 'Vallenar',
            latitude: '-28.57617000',
            longitude: '-70.75938000')
      ]),
      State(id: 2828, name: 'Aysén Region', stateCode: 'AI', cities: [
        City(
            id: 18962,
            name: 'Chile Chico',
            latitude: '-46.54100000',
            longitude: '-71.72375000'),
        City(
            id: 18966,
            name: 'Cochrane',
            latitude: '-47.25570000',
            longitude: '-72.56950000'),
        City(
            id: 18976,
            name: 'Coyhaique',
            latitude: '-45.57524000',
            longitude: '-72.06619000'),
        City(
            id: 18991,
            name: 'La Junta',
            latitude: '-43.97434000',
            longitude: '-72.40554000'),
        City(
            id: 19030,
            name: 'Provincia Capitán Prat',
            latitude: '-47.97550000',
            longitude: '-73.54155000'),
        City(
            id: 19032,
            name: 'Provincia de Aisén',
            latitude: '-45.35626000',
            longitude: '-72.57322000'),
        City(
            id: 19049,
            name: 'Provincia de Coyhaique',
            latitude: '-45.63037000',
            longitude: '-72.32025000'),
        City(
            id: 19031,
            name: 'Provincia General Carrera',
            latitude: '-46.63435000',
            longitude: '-72.31476000'),
        City(
            id: 19082,
            name: 'Puerto Aysén',
            latitude: '-45.40303000',
            longitude: '-72.69184000'),
        City(
            id: 19083,
            name: 'Puerto Chacabuco',
            latitude: '-45.46667000',
            longitude: '-72.81667000'),
        City(
            id: 19084,
            name: 'Puerto Cisnes',
            latitude: '-44.74736000',
            longitude: '-72.69695000')
      ]),
      State(id: 2827, name: 'Bío Bío Region', stateCode: 'BI', cities: [
        City(
            id: 18947,
            name: 'Arauco',
            latitude: '-37.24630000',
            longitude: '-73.31752000'),
        City(
            id: 18951,
            name: 'Cabrero',
            latitude: '-37.03394000',
            longitude: '-72.40468000'),
        City(
            id: 18958,
            name: 'Cañete',
            latitude: '-37.80128000',
            longitude: '-73.39616000'),
        City(
            id: 18961,
            name: 'Chiguayante',
            latitude: '-36.92560000',
            longitude: '-73.02841000'),
        City(
            id: 18970,
            name: 'Concepción',
            latitude: '-36.82699000',
            longitude: '-73.04977000'),
        City(
            id: 18974,
            name: 'Coronel',
            latitude: '-37.03386000',
            longitude: '-73.14019000'),
        City(
            id: 18977,
            name: 'Curanilahue',
            latitude: '-37.47793000',
            longitude: '-73.34495000'),
        City(
            id: 18996,
            name: 'Laja',
            latitude: '-37.28415000',
            longitude: '-72.71105000'),
        City(
            id: 19001,
            name: 'Lebu',
            latitude: '-37.60825000',
            longitude: '-73.65356000'),
        City(
            id: 19009,
            name: 'Los Ángeles',
            latitude: '-37.46973000',
            longitude: '-72.35366000'),
        City(
            id: 19010,
            name: 'Lota',
            latitude: '-37.08994000',
            longitude: '-73.15770000'),
        City(
            id: 19015,
            name: 'Mulchén',
            latitude: '-37.71893000',
            longitude: '-72.24099000'),
        City(
            id: 19016,
            name: 'Nacimiento',
            latitude: '-37.50253000',
            longitude: '-72.67307000'),
        City(
            id: 19024,
            name: 'Penco',
            latitude: '-36.74075000',
            longitude: '-72.99528000'),
        City(
            id: 19034,
            name: 'Provincia de Arauco',
            latitude: '-37.74174000',
            longitude: '-73.35799000'),
        City(
            id: 19036,
            name: 'Provincia de Biobío',
            latitude: '-37.59511000',
            longitude: '-71.89553000'),
        City(
            id: 19046,
            name: 'Provincia de Concepción',
            latitude: '-36.95773000',
            longitude: '-72.89674000'),
        City(
            id: 19114,
            name: 'Talcahuano',
            latitude: '-36.72494000',
            longitude: '-73.11684000'),
        City(
            id: 19119,
            name: 'Tomé',
            latitude: '-36.61756000',
            longitude: '-72.95593000'),
        City(
            id: 19131,
            name: 'Yumbel',
            latitude: '-37.09820000',
            longitude: '-72.56084000')
      ]),
      State(id: 2825, name: 'Coquimbo Region', stateCode: 'CO', cities: [
        City(
            id: 18973,
            name: 'Coquimbo',
            latitude: '-29.95332000',
            longitude: '-71.33947000'),
        City(
            id: 18988,
            name: 'Illapel',
            latitude: '-31.63349000',
            longitude: '-71.16967000'),
        City(
            id: 18994,
            name: 'La Serena',
            latitude: '-29.90453000',
            longitude: '-71.24894000'),
        City(
            id: 19014,
            name: 'Monte Patria',
            latitude: '-30.69496000',
            longitude: '-70.95770000'),
        City(
            id: 19019,
            name: 'Ovalle',
            latitude: '-30.60106000',
            longitude: '-71.19901000'),
        City(
            id: 19044,
            name: 'Provincia de Choapa',
            latitude: '-31.71090000',
            longitude: '-70.99263000'),
        City(
            id: 19052,
            name: 'Provincia de Elqui',
            latitude: '-29.73588000',
            longitude: '-70.64455000'),
        City(
            id: 19056,
            name: 'Provincia de Limarí',
            latitude: '-30.75000000',
            longitude: '-71.00000000'),
        City(
            id: 19099,
            name: 'Salamanca',
            latitude: '-31.77922000',
            longitude: '-70.96389000'),
        City(
            id: 19125,
            name: 'Vicuña',
            latitude: '-30.03541000',
            longitude: '-70.71274000')
      ]),
      State(id: 2835, name: 'Los Lagos Region', stateCode: 'LL', cities: [
        City(
            id: 18944,
            name: 'Ancud',
            latitude: '-41.87070000',
            longitude: '-73.81622000'),
        City(
            id: 18953,
            name: 'Calbuco',
            latitude: '-41.77338000',
            longitude: '-73.13049000'),
        City(
            id: 18956,
            name: 'Castro',
            latitude: '-42.47210000',
            longitude: '-73.77319000'),
        City(
            id: 18959,
            name: 'Chaitén',
            latitude: '-42.91596000',
            longitude: '-72.70632000'),
        City(
            id: 18965,
            name: 'Chonchi',
            latitude: '-42.62387000',
            longitude: '-73.77500000'),
        City(
            id: 18980,
            name: 'Dalcahue',
            latitude: '-42.37845000',
            longitude: '-73.65011000'),
        City(
            id: 18984,
            name: 'Futaleufú',
            latitude: '-43.18492000',
            longitude: '-71.86722000'),
        City(
            id: 18990,
            name: 'La Ensenada',
            latitude: '-41.20746000',
            longitude: '-72.53840000'),
        City(
            id: 19018,
            name: 'Osorno',
            latitude: '-40.57395000',
            longitude: '-73.13348000'),
        City(
            id: 19021,
            name: 'Palena',
            latitude: '-43.61876000',
            longitude: '-71.80434000'),
        City(
            id: 19043,
            name: 'Provincia de Chiloé',
            latitude: '-42.57471000',
            longitude: '-73.96062000'),
        City(
            id: 19058,
            name: 'Provincia de Llanquihue',
            latitude: '-41.34285000',
            longitude: '-72.65800000'),
        City(
            id: 19065,
            name: 'Provincia de Osorno',
            latitude: '-40.77939000',
            longitude: '-72.95299000'),
        City(
            id: 19066,
            name: 'Provincia de Palena',
            latitude: '-43.16212000',
            longitude: '-72.47818000'),
        City(
            id: 19085,
            name: 'Puerto Montt',
            latitude: '-41.46930000',
            longitude: '-72.94237000'),
        City(
            id: 19087,
            name: 'Puerto Varas',
            latitude: '-41.31946000',
            longitude: '-72.98538000'),
        City(
            id: 19089,
            name: 'Purranque',
            latitude: '-40.91305000',
            longitude: '-73.15913000'),
        City(
            id: 19091,
            name: 'Quellón',
            latitude: '-43.11819000',
            longitude: '-73.61661000')
      ]),
      State(id: 2834, name: 'Los Ríos Region', stateCode: 'LR', cities: [
        City(
            id: 18975,
            name: 'Corral',
            latitude: '-39.88730000',
            longitude: '-73.43101000'),
        City(
            id: 18995,
            name: 'La Unión',
            latitude: '-40.29313000',
            longitude: '-73.08167000'),
        City(
            id: 18998,
            name: 'Las Animas',
            latitude: '-39.80867000',
            longitude: '-73.21821000'),
        City(
            id: 18999,
            name: 'Las Gaviotas',
            latitude: '-39.86653000',
            longitude: '-73.18834000'),
        City(
            id: 19022,
            name: 'Panguipulli',
            latitude: '-39.64355000',
            longitude: '-72.33269000'),
        City(
            id: 19075,
            name: 'Provincia de Valdivia',
            latitude: '-39.80273000',
            longitude: '-72.54690000'),
        City(
            id: 19078,
            name: 'Provincia del Ranco',
            latitude: '-40.13689000',
            longitude: '-72.37793000'),
        City(
            id: 19090,
            name: 'Puyehue',
            latitude: '-40.65944000',
            longitude: '-72.60172000'),
        City(
            id: 19098,
            name: 'Río Bueno',
            latitude: '-40.33494000',
            longitude: '-72.95564000'),
        City(
            id: 19121,
            name: 'Valdivia',
            latitude: '-39.81422000',
            longitude: '-73.24589000')
      ]),
      State(
          id: 2836,
          name: 'Magellan and the Chilean Antarctic Region',
          stateCode: 'MA',
          cities: [
            City(
                id: 18979,
                name: 'Cámeron',
                latitude: '-53.63988000',
                longitude: '-69.64693000'),
            City(
                id: 19028,
                name: 'Porvenir',
                latitude: '-53.29600000',
                longitude: '-70.36629000'),
            City(
                id: 19029,
                name: 'Provincia Antártica Chilena',
                latitude: '-55.02250000',
                longitude: '-69.22781000'),
            City(
                id: 19060,
                name: 'Provincia de Magallanes',
                latitude: '-52.91667000',
                longitude: '-71.08333000'),
            City(
                id: 19073,
                name: 'Provincia de Tierra del Fuego',
                latitude: '-53.66083000',
                longitude: '-69.45173000'),
            City(
                id: 19077,
                name: 'Provincia de Última Esperanza',
                latitude: '-50.75000000',
                longitude: '-74.00000000'),
            City(
                id: 19086,
                name: 'Puerto Natales',
                latitude: '-51.72987000',
                longitude: '-72.50603000'),
            City(
                id: 19088,
                name: 'Punta Arenas',
                latitude: '-53.15483000',
                longitude: '-70.91129000')
          ]),
      State(id: 2833, name: 'Maule Region', stateCode: 'ML', cities: [
        City(
            id: 18957,
            name: 'Cauquenes',
            latitude: '-35.96710000',
            longitude: '-72.32248000'),
        City(
            id: 18968,
            name: 'Colbún',
            latitude: '-35.69494000',
            longitude: '-71.40568000'),
        City(
            id: 18971,
            name: 'Constitución',
            latitude: '-35.33321000',
            longitude: '-72.41156000'),
        City(
            id: 18978,
            name: 'Curicó',
            latitude: '-34.98279000',
            longitude: '-71.23943000'),
        City(
            id: 19003,
            name: 'Linares',
            latitude: '-35.84667000',
            longitude: '-71.59308000'),
        City(
            id: 19007,
            name: 'Longaví',
            latitude: '-35.96496000',
            longitude: '-71.68360000'),
        City(
            id: 19013,
            name: 'Molina',
            latitude: '-35.11428000',
            longitude: '-71.28232000'),
        City(
            id: 19023,
            name: 'Parral',
            latitude: '-36.14311000',
            longitude: '-71.82605000'),
        City(
            id: 19039,
            name: 'Provincia de Cauquenes',
            latitude: '-35.96828000',
            longitude: '-72.32918000'),
        City(
            id: 19050,
            name: 'Provincia de Curicó',
            latitude: '-35.04932000',
            longitude: '-71.09148000'),
        City(
            id: 19057,
            name: 'Provincia de Linares',
            latitude: '-36.02955000',
            longitude: '-71.43099000'),
        City(
            id: 19072,
            name: 'Provincia de Talca',
            latitude: '-35.43780000',
            longitude: '-71.35326000'),
        City(
            id: 19096,
            name: 'Rauco',
            latitude: '-34.92546000',
            longitude: '-71.31722000'),
        City(
            id: 19104,
            name: 'San Clemente',
            latitude: '-35.53777000',
            longitude: '-71.48700000'),
        City(
            id: 19106,
            name: 'San Javier',
            latitude: '-35.59520000',
            longitude: '-71.72924000'),
        City(
            id: 19113,
            name: 'Talca',
            latitude: '-35.42640000',
            longitude: '-71.65542000'),
        City(
            id: 19117,
            name: 'Teno',
            latitude: '-34.87055000',
            longitude: '-71.16219000')
      ]),
      State(id: 2831, name: 'Ñuble Region', stateCode: 'NB', cities: [
        City(
            id: 18950,
            name: 'Bulnes',
            latitude: '-36.74232000',
            longitude: '-72.29854000'),
        City(
            id: 18963,
            name: 'Chillán',
            latitude: '-36.60664000',
            longitude: '-72.10344000'),
        City(
            id: 18967,
            name: 'Coihueco',
            latitude: '-36.62785000',
            longitude: '-71.83068000'),
        City(
            id: 19094,
            name: 'Quirihue',
            latitude: '-36.27998000',
            longitude: '-72.54118000'),
        City(
            id: 19103,
            name: 'San Carlos',
            latitude: '-36.42477000',
            longitude: '-71.95800000')
      ]),
      State(id: 2838, name: 'O\'Higgins', stateCode: 'LI', cities: [
        City(
            id: 18964,
            name: 'Chimbarongo',
            latitude: '-34.71247000',
            longitude: '-71.04340000'),
        City(
            id: 18985,
            name: 'Graneros',
            latitude: '-34.06863000',
            longitude: '-70.72747000'),
        City(
            id: 19011,
            name: 'Machalí',
            latitude: '-34.18082000',
            longitude: '-70.64933000'),
        City(
            id: 19037,
            name: 'Provincia de Cachapoal',
            latitude: '-34.29987000',
            longitude: '-70.72061000'),
        City(
            id: 19038,
            name: 'Provincia de Cardenal Caro',
            latitude: '-34.38651000',
            longitude: '-71.94500000'),
        City(
            id: 19045,
            name: 'Provincia de Colchagua',
            latitude: '-34.69485000',
            longitude: '-71.07606000'),
        City(
            id: 19095,
            name: 'Rancagua',
            latitude: '-34.17083000',
            longitude: '-70.74444000'),
        City(
            id: 19097,
            name: 'Rengo',
            latitude: '-34.40639000',
            longitude: '-70.85834000'),
        City(
            id: 19108,
            name: 'San Vicente',
            latitude: '-34.43333000',
            longitude: '-71.08333000'),
        City(
            id: 19109,
            name: 'San Vicente de Tagua Tagua',
            latitude: '-34.43859000',
            longitude: '-71.07751000'),
        City(
            id: 19110,
            name: 'Santa Cruz',
            latitude: '-34.63881000',
            longitude: '-71.36576000')
      ]),
      State(
          id: 2824,
          name: 'Santiago Metropolitan Region',
          stateCode: 'RM',
          cities: [
            City(
                id: 18949,
                name: 'Buin',
                latitude: '-33.73257000',
                longitude: '-70.74281000'),
            City(
                id: 18960,
                name: 'Chicureo Abajo',
                latitude: '-33.28379000',
                longitude: '-70.65333000'),
            City(
                id: 18982,
                name: 'El Monte',
                latitude: '-33.67969000',
                longitude: '-70.98482000'),
            City(
                id: 18993,
                name: 'La Pintana',
                latitude: '-33.58331000',
                longitude: '-70.63419000'),
            City(
                id: 18997,
                name: 'Lampa',
                latitude: '-33.28630000',
                longitude: '-70.87561000'),
            City(
                id: 19005,
                name: 'Lo Prado',
                latitude: '-33.44430000',
                longitude: '-70.72552000'),
            City(
                id: 19012,
                name: 'Melipilla',
                latitude: '-33.68909000',
                longitude: '-71.21528000'),
            City(
                id: 19020,
                name: 'Paine',
                latitude: '-33.80796000',
                longitude: '-70.74109000'),
            City(
                id: 19026,
                name: 'Peñaflor',
                latitude: '-33.60627000',
                longitude: '-70.87649000'),
            City(
                id: 19041,
                name: 'Provincia de Chacabuco',
                latitude: '-33.15940000',
                longitude: '-70.81650000'),
            City(
                id: 19048,
                name: 'Provincia de Cordillera',
                latitude: '-33.67921000',
                longitude: '-70.54665000'),
            City(
                id: 19061,
                name: 'Provincia de Maipo',
                latitude: '-33.83333000',
                longitude: '-70.75000000'),
            City(
                id: 19064,
                name: 'Provincia de Melipilla',
                latitude: '-33.75000000',
                longitude: '-71.16667000'),
            City(
                id: 19070,
                name: 'Provincia de Santiago',
                latitude: '-33.33333000',
                longitude: '-70.66667000'),
            City(
                id: 19071,
                name: 'Provincia de Talagante',
                latitude: '-33.66667000',
                longitude: '-70.91667000'),
            City(
                id: 19081,
                name: 'Puente Alto',
                latitude: '-33.61169000',
                longitude: '-70.57577000'),
            City(
                id: 19102,
                name: 'San Bernardo',
                latitude: '-33.59217000',
                longitude: '-70.69960000'),
            City(
                id: 19111,
                name: 'Santiago',
                latitude: '-33.45694000',
                longitude: '-70.64827000'),
            City(
                id: 19112,
                name: 'Talagante',
                latitude: '-33.66386000',
                longitude: '-70.92734000'),
            City(
                id: 19128,
                name: 'Villa Presidente Frei, Ñuñoa, Santiago, Chile',
                latitude: '-33.46069000',
                longitude: '-70.58024000')
          ]),
      State(id: 2837, name: 'Tarapacá Region', stateCode: 'TA', cities: [
        City(
            id: 18989,
            name: 'Iquique',
            latitude: '-20.21326000',
            longitude: '-70.15027000'),
        City(
            id: 19054,
            name: 'Provincia de Iquique',
            latitude: '-20.24158000',
            longitude: '-70.08728000'),
        City(
            id: 19079,
            name: 'Provincia del Tamarugal',
            latitude: '-20.26445000',
            longitude: '-69.81606000')
      ]),
      State(id: 2830, name: 'Valparaíso', stateCode: 'VS', cities: [
        City(
            id: 18955,
            name: 'Cartagena',
            latitude: '-33.55384000',
            longitude: '-71.60761000'),
        City(
            id: 18986,
            name: 'Hacienda La Calera',
            latitude: '-32.78333000',
            longitude: '-71.21667000'),
        City(
            id: 18987,
            name: 'Hanga Roa',
            latitude: '-27.15474000',
            longitude: '-109.43241000'),
        City(
            id: 18992,
            name: 'La Ligua',
            latitude: '-32.45242000',
            longitude: '-71.23106000'),
        City(
            id: 19002,
            name: 'Limache',
            latitude: '-33.01667000',
            longitude: '-71.26667000'),
        City(
            id: 19004,
            name: 'Llaillay',
            latitude: '-32.84043000',
            longitude: '-70.95623000'),
        City(
            id: 19008,
            name: 'Los Andes',
            latitude: '-32.83369000',
            longitude: '-70.59827000'),
        City(
            id: 19025,
            name: 'Petorca Province',
            latitude: '-32.33333000',
            longitude: '-71.00000000'),
        City(
            id: 19055,
            name: 'Provincia de Isla de Pascua',
            latitude: '-27.11048000',
            longitude: '-109.29749000'),
        City(
            id: 19059,
            name: 'Provincia de Los Andes',
            latitude: '-32.82556000',
            longitude: '-70.33518000'),
        City(
            id: 19063,
            name: 'Provincia de Marga Marga',
            latitude: '-33.04378000',
            longitude: '-71.39465000'),
        City(
            id: 19068,
            name: 'Provincia de Quillota',
            latitude: '-32.80753000',
            longitude: '-71.17957000'),
        City(
            id: 19069,
            name: 'Provincia de San Felipe de Aconcagua',
            latitude: '-32.60401000',
            longitude: '-70.65930000'),
        City(
            id: 19076,
            name: 'Provincia de Valparaíso',
            latitude: '-33.06105000',
            longitude: '-71.59241000'),
        City(
            id: 19092,
            name: 'Quillota',
            latitude: '-32.88341000',
            longitude: '-71.24882000'),
        City(
            id: 19093,
            name: 'Quilpué',
            latitude: '-33.04752000',
            longitude: '-71.44249000'),
        City(
            id: 19100,
            name: 'San Antonio',
            latitude: '-33.59473000',
            longitude: '-71.60746000'),
        City(
            id: 19101,
            name: 'San Antonio Province',
            latitude: '-33.58333000',
            longitude: '-71.50000000'),
        City(
            id: 19105,
            name: 'San Felipe',
            latitude: '-32.74976000',
            longitude: '-70.72584000'),
        City(
            id: 19123,
            name: 'Valparaíso',
            latitude: '-33.03600000',
            longitude: '-71.62963000'),
        City(
            id: 19127,
            name: 'Villa Alemana',
            latitude: '-33.04222000',
            longitude: '-71.37333000'),
        City(
            id: 19130,
            name: 'Viña del Mar',
            latitude: '-33.02457000',
            longitude: '-71.55183000')
      ])
    ]);
